#!/usr/bin/env python3
"""Check Reference Independence Guard for AI-Agent Gold Standards (Specification 28, Section 5).

Verifies:
1. Reference runners do NOT import production system code (`app.api`, `app.services`, etc.).
2. Reference scripts do not overwrite expected.json files during standard test executions.
3. Expected goldens are not generated by executing production runners against themselves.
"""

from __future__ import annotations

import ast
import re
import sys
from pathlib import Path

import yaml

PROJECT_ROOT = Path(__file__).resolve().parent.parent
GOLDENS_DIR = PROJECT_ROOT / "tests" / "goldens"
GOLDEN_PLANS_DIR = PROJECT_ROOT / "golden-plans"
FIXTURES_REF_DIR = PROJECT_ROOT / "apps" / "api" / "tests" / "fixtures" / "advanced" / "reference"

PROHIBITED_IMPORTS = [
    "app.api",
    "app.services",
    "app.main",
]

RUNNER_TARGET_PATTERN = re.compile(r"""["']([^"']+\.(?:py|R))["']""")


def check_python_script_imports(file_path: Path) -> list[str]:
    violations: list[str] = []
    if not file_path.exists() or file_path.suffix != ".py":
        return violations

    try:
        tree = ast.parse(file_path.read_text(encoding="utf-8"), filename=str(file_path))
    except Exception as exc:
        violations.append(f"{file_path}: Failed to parse Python AST: {exc}")
        return violations

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                for prohibited in PROHIBITED_IMPORTS:
                    if alias.name.startswith(prohibited):
                        violations.append(
                            f"{file_path}:{node.lineno}: Prohibited production import '{alias.name}'"
                        )
        elif isinstance(node, ast.ImportFrom):
            module = node.module or ""
            for prohibited in PROHIBITED_IMPORTS:
                if module.startswith(prohibited):
                    violations.append(
                        f"{file_path}:{node.lineno}: Prohibited production import from '{module}'"
                    )

    return violations


def check_no_overwrite_in_ci() -> list[str]:
    """Verify that CI workflows and standard test suites do not allow expected goldens overwrite."""
    violations: list[str] = []
    pytest_files = list(PROJECT_ROOT.glob("apps/api/tests/**/*.py"))
    for py_file in pytest_files:
        content = py_file.read_text(encoding="utf-8")
        if (
            "expected_path.write_text(" in content
            and "OVERWRITE_GOLDENS" not in content
            and "golden-refresh" not in content
        ):
            # Check if this is an explicit golden generation script or standard test
            if "generate" not in py_file.name:
                violations.append(
                    f"{py_file}: Standard test file appears to dynamically write/overwrite expected goldens."
                )
    return violations


def check_network_isolation_and_write_defense(script_path: Path) -> list[str]:
    """INFRA-01: Ensure reference runner scripts do not make unpinned external HTTP requests or write into expected/."""
    violations: list[str] = []
    if script_path.suffix != ".py":
        return violations
    text = script_path.read_text(encoding="utf-8")
    if "requests.get(" in text or "requests.post(" in text or "urllib.request" in text:
        if "ALLOW_NETWORK" not in text:
            violations.append(f"{script_path}: Reference runner contains unisolated network request call.")
    if "expected/expected.json" in text and ("open(" in text and ("'w'" in text or '"w"' in text)):
        if "OVERWRITE_GOLDENS" not in text:
            violations.append(f"{script_path}: Reference runner script contains unsafe write to expected/expected.json.")
    return violations


def _runner_targets(script_path: Path) -> set[str]:
    if not script_path.exists():
        return set()
    text = script_path.read_text(encoding="utf-8")
    return {
        Path(match.replace("\\", "/")).name.lower()
        for match in RUNNER_TARGET_PATTERN.findall(text)
        if Path(match.replace("\\", "/")).name.lower() != "run.py"
    }


def check_primary_secondary_separation() -> list[str]:
    """Verify declared and executable primary/secondary stacks are substantively distinct."""
    violations: list[str] = []
    plans: dict[str, dict[str, object]] = {}
    for plan_path in GOLDEN_PLANS_DIR.glob("*.yaml"):
        plan = yaml.safe_load(plan_path.read_text(encoding="utf-8"))
        capability = plan.get("capabilityId")
        if capability:
            plans[str(capability)] = plan

    for manifest_path in GOLDENS_DIR.glob("*/cases/*/manifest.yaml"):
        manifest = yaml.safe_load(manifest_path.read_text(encoding="utf-8"))
        primary = manifest.get("primaryReference")
        secondary = manifest.get("secondaryReference")
        if not primary or not secondary:
            continue
        case_dir = manifest_path.parent
        capability = str(manifest.get("identity", {}).get("capabilityId", ""))
        plan = plans.get(capability, {})
        evidence_plan = plan.get("evidencePlan", {}) if isinstance(plan, dict) else {}
        planned_secondary = (
            evidence_plan.get("secondary", {}).get("tool")
            if isinstance(evidence_plan, dict)
            and isinstance(evidence_plan.get("secondary"), dict)
            else None
        )
        primary_runner = case_dir / "reference" / "primary" / "run.py"
        secondary_runner = case_dir / "reference" / "secondary" / "run.py"
        if not primary_runner.exists() or not secondary_runner.exists():
            continue
        primary_text = primary_runner.read_text(encoding="utf-8")
        secondary_text = secondary_runner.read_text(encoding="utf-8")
        declared_secondary = secondary.get("engine")
        if (
            "run_independent_secondary.py" in secondary_text
            and planned_secondary
            and declared_secondary != planned_secondary
        ):
            violations.append(
                f"{manifest_path}: secondary engine '{declared_secondary}' does not match "
                f"Golden plan tool '{planned_secondary}'."
            )
        if primary_text == secondary_text:
            violations.append(
                f"{case_dir}: primary and secondary reference runners are byte-identical."
            )
        common_targets = _runner_targets(primary_runner) & _runner_targets(secondary_runner)
        if common_targets:
            violations.append(
                f"{case_dir}: primary and secondary invoke the same generator target(s): "
                f"{', '.join(sorted(common_targets))}."
            )
        if str(planned_secondary).startswith("python_"):
            if "Rscript" in secondary_text or ".R\"" in secondary_text or ".R'" in secondary_text:
                violations.append(
                    f"{secondary_runner}: Python secondary plan delegates to an R runner."
                )
            if "run_statistical_reference.py" in secondary_text:
                violations.append(
                    f"{secondary_runner}: secondary delegates to the primary reference dispatcher."
                )

    return violations


def main() -> int:
    print("==========================================================")
    print("Checking Gold Standard Reference Independence (Spec 28)")
    print("==========================================================")

    violations: list[str] = []

    # Check reference scripts in fixtures and goldens
    reference_scripts: list[Path] = []
    if GOLDENS_DIR.exists():
        reference_scripts.extend(GOLDENS_DIR.glob("**/*.py"))
        reference_scripts.extend(GOLDENS_DIR.glob("**/*.R"))
    if FIXTURES_REF_DIR.exists():
        reference_scripts.extend(FIXTURES_REF_DIR.glob("*.py"))
        reference_scripts.extend(FIXTURES_REF_DIR.glob("*.R"))

    for script in reference_scripts:
        if script.suffix == ".py":
            violations.extend(check_python_script_imports(script))
            violations.extend(check_network_isolation_and_write_defense(script))

    violations.extend(check_no_overwrite_in_ci())
    violations.extend(check_primary_secondary_separation())

    if violations:
        print(f"\n[FAIL] Found {len(violations)} reference independence violations:\n")
        for v in violations:
            print(f"  - {v}")
        return 1

    print("\n[PASS] All reference scripts adhere to independence rules.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
