# Golden-standard tests: product runner vs the OFFICIAL PROCESS 5.0 R macro.
#
# Golden values live in engine/R/tests/reference/process-goldens.json,
# generated by generate-process-goldens.R with the official macro (never by
# the product runner). These tests execute the real run_analysis.R entry on
# the identical synthetic data and compare path coefficients, indirect /
# conditional effects, bootstrap intervals and the JN grid.
#
# Tolerances come from the golden provenance and must not be widened to
# accept drift.

process_goldens <- local({
  path <- file.path(
    Sys.getenv("RESEARCHPATH_PROJECT_ROOT"),
    "engine", "R", "tests", "reference", "process-goldens.json"
  )
  jsonlite::fromJSON(path, simplifyVector = FALSE)
})

process_golden_models <- process_goldens$models
process_tolerance <- process_goldens$provenance$tolerance

make_process_spec <- function(model_number) {
  edges <- switch(
    as.character(model_number),
    "1" = list(c("x", "y")),
    "4" = list(c("x", "m1"), c("m1", "y"), c("x", "y")),
    "6" = list(
      c("x", "m1"), c("x", "m2"),
      c("m1", "y"), c("m2", "y"),
      c("x", "y"), c("m1", "m2")
    ),
    "7" = list(c("x", "m1"), c("m1", "y"), c("x", "y")),
    "14" = list(c("x", "m1"), c("m1", "y"), c("x", "y"))
  )
  moderations <- switch(
    as.character(model_number),
    "1" = list(list(moderator = "w", source = "x", target = "y")),
    "7" = list(list(moderator = "w", source = "x", target = "m1")),
    "14" = list(list(moderator = "w", source = "m1", target = "y")),
    list()
  )
  nodes <- list(
    list(id = "x", variableId = "var_x", label = "X", kind = "observed",
         role = "x", dataType = "continuous"),
    list(id = "y", variableId = "var_y", label = "Y", kind = "observed",
         role = "y", dataType = "continuous")
  )
  if (model_number %in% c(4, 6, 7, 14)) {
    nodes <- c(
      nodes,
      list(list(id = "m1", variableId = "var_m1", label = "M1",
                kind = "observed", role = "m", dataType = "continuous"))
    )
  }
  if (model_number == 6) {
    nodes <- c(
      nodes,
      list(list(id = "m2", variableId = "var_m2", label = "M2",
                kind = "observed", role = "m", dataType = "continuous"))
    )
  }
  if (model_number %in% c(1, 7, 14)) {
    nodes <- c(
      nodes,
      list(list(id = "w", variableId = "var_w", label = "W",
                kind = "observed", role = "w", dataType = "continuous"))
    )
  }
  edge_items <- lapply(edges, function(edge) {
    list(
      id = paste0("edge_", edge[1], "_", edge[2]),
      from = edge[1], to = edge[2], kind = "regression"
    )
  })
  edge_id_by_pair <- setNames(
    vapply(edge_items, function(edge) edge$id, character(1)),
    vapply(edge_items, function(edge) paste0(edge$from, "->", edge$to), character(1))
  )
  moderation_items <- lapply(seq_along(moderations), function(index) {
    mod <- moderations[[index]]
    list(
      id = paste0("mod_", index - 1L),
      moderatorNodeId = mod$moderator,
      targetEdgeId = edge_id_by_pair[[paste0(mod$source, "->", mod$target)]],
      # Official macro names the interaction term "int_1"; keep the same id
      # so golden comparisons line up.
      productTermId = "int_1"
    )
  })
  node_ids <- vapply(nodes, function(node) node$id, character(1))
  centering_ids <- node_ids[node_ids != "y"]
  list(
    schemaVersion = "1.0.0",
    modelId = paste0("catalog_model_", model_number),
    name = paste0("PROCESS Model ", model_number),
    datasetVersionId = "derived_catalog",
    design = list(
      timeStructure = "cross_sectional",
      clustering = "none",
      claimMode = "associational"
    ),
    nodes = nodes,
    edges = edge_items,
    moderations = moderation_items,
    covariates = list(),
    estimation = list(
      family = "ols",
      standardErrors = "classical",
      confidenceLevel = 0.95,
      bootstrap = list(
        enabled = FALSE,
        replicates = 5000,
        method = "percentile",
        seed = 20260730
      ),
      missing = "complete_cases_per_model",
      centering = list(method = "mean", nodeIds = centering_ids),
      reportScale = "unstandardized_primary"
    )
  )
}

write_golden_data <- function(path) {
  row <- 1:240
  x <- sin(row * 0.37) + cos(row * 0.11)
  w <- cos(row * 0.23) + sin(row * 0.07)
  z <- sin(row * 0.19) - cos(row * 0.13)
  m1 <- 0.4 * x + 0.18 * w - 0.12 * z + sin(row * 1.31) * 0.55
  m2 <- 0.25 * m1 + 0.15 * x + 0.1 * w + cos(row * 0.71) * 0.45
  y <- 0.22 * x + 0.36 * m1 + 0.14 * w - 0.09 * z +
    0.17 * m1 * w - 0.11 * m1 * z + 0.08 * m1 * w * z +
    cos(row * 1.17) * 0.6
  data <- data.frame(
    var_x = x, var_m1 = m1, var_m2 = m2, var_y = y, var_w = w, var_z = z
  )
  # NOT pre-centered: the product runner centers per spec (method=mean on
  # x/m1/w/z), which is numerically identical to the generator's manual
  # centering before the official macro call.
  write.csv(data, path, row.names = FALSE)
}

run_process_runner <- function(spec, data_path, work_dir) {
  input_path <- file.path(work_dir, "input.json")
  output_path <- file.path(work_dir, "output.json")
  writeLines(
    jsonlite::toJSON(
      list(
        modelSpec = spec,
        dataPath = data_path,
        progressPath = file.path(work_dir, "progress.json"),
        cancelPath = file.path(work_dir, "cancel.json")
      ),
      auto_unbox = TRUE, digits = NA
    ),
    input_path
  )
  runner <- file.path(
    Sys.getenv("RESEARCHPATH_PROJECT_ROOT"),
    "engine", "R", "run_analysis.R"
  )
  rscript <- file.path(R.home("bin"), "Rscript.exe")
  status <- system2(
    rscript, c("--vanilla", shQuote(runner), shQuote(input_path), shQuote(output_path)),
    stdout = TRUE, stderr = TRUE
  )
  if (!file.exists(output_path)) {
    stop("run_analysis.R failed: ", paste(status, collapse = "\n"))
  }
  jsonlite::fromJSON(output_path, simplifyVector = FALSE)
}

process_equation_coeffs <- function(result) {
  stats::setNames(
    lapply(result$equations, function(equation) {
      stats::setNames(
        vapply(equation$coefficients, function(coeff) coeff$estimate, numeric(1)),
        vapply(equation$coefficients, function(coeff) coeff$term, character(1))
      )
    }),
    vapply(result$equations, function(equation) {
      trimws(strsplit(equation$formula, "~", fixed = TRUE)[[1]][1])
    }, character(1))
  )
}

expect_coefficients_match <- function(actual, expected_rows, label, tolerance) {
  expected <- stats::setNames(
    vapply(expected_rows, function(row) row$coeff, numeric(1)),
    vapply(expected_rows, function(row) row$term, character(1))
  )
  for (term in names(expected)) {
    if (term == "constant") next
    # Runner equations are keyed by node ids ("x", "m1"); the official macro
    # prints variable names ("var_x", "var_m1").
    node_term <- sub("^var_", "", term)
    expect_true(
      node_term %in% names(actual),
      info = paste0(label, ": term ", node_term, " missing from equation")
    )
    expect_equal(
      unname(actual[[node_term]]), unname(expected[[term]]),
      tolerance = tolerance,
      info = paste0(label, ": coefficient ", node_term)
    )
  }
}

golden_equation <- function(model_key, outcome) {
  # equations is a JSON array in outcome order (m equations first, y last).
  equations <- process_golden_models[[model_key]]$equations
  if (identical(outcome, "y")) return(equations[[length(equations)]])
  equations[[1]]
}

golden_indirect <- function(model_key, field = "indirect") {
  process_golden_models[[model_key]][[field]]
}

# --- Point-estimate tests (bootstrap disabled, fast) ----------------------
# Mediation templates (4/6/7/14) require bootstrap.enabled=true in the
# runner, so their point estimates are asserted inside the bootstrap tests
# below; only the pure-moderation template (1) runs bootstrap-free here.

test_that("model_1 path coefficients match official PROCESS macro", {
  work <- tempfile(pattern = "rp-process-")
  dir.create(work)
  data_path <- file.path(work, "data.csv")
  write_golden_data(data_path)
  spec <- make_process_spec(1)
  result <- run_process_runner(spec, data_path, work)
  actual <- process_equation_coeffs(result)
  key <- "model_1"
  tolerance <- process_tolerance$coefficient
  expect_coefficients_match(
    actual[["y"]], process_golden_models[[key]]$equations[[1]],
    key, tolerance
  )
})

# --- Bootstrap interval tests (5000 replicates, same seed as golden) -------

test_that("model_4 percentile bootstrap intervals match official macro", {
  work <- tempfile(pattern = "rp-process-boot-")
  dir.create(work)
  data_path <- file.path(work, "data.csv")
  write_golden_data(data_path)
  spec <- make_process_spec(4)
  spec$estimation$bootstrap$enabled <- TRUE
  spec$estimation$bootstrap$replicates <- 5000
  spec$estimation$bootstrap$method <- "percentile"
  spec$estimation$bootstrap$seed <- 20260730
  result <- run_process_runner(spec, data_path, work)

  actual <- process_equation_coeffs(result)
  expect_coefficients_match(
    actual[["m1"]], process_golden_models[["model_4"]]$equations[[1]],
    "model_4", process_tolerance$coefficient
  )
  expect_coefficients_match(
    actual[["y"]], process_golden_models[["model_4"]]$equations[[2]],
    "model_4", process_tolerance$coefficient
  )

  golden <- golden_indirect("model_4")[[1]]
  indirect <- Filter(function(effect) effect$type == "indirect", result$effects)[[1]]
  interval <- indirect$confidenceInterval
  expect_equal(
    unname(indirect$estimate), golden$effect,
    tolerance = process_tolerance$effect
  )
  expect_equal(
    interval$lower, golden$bootLLCI,
    tolerance = process_tolerance$bootstrapInterval,
    info = "percentile bootstrap lower bound"
  )
  expect_equal(
    interval$upper, golden$bootULCI,
    tolerance = process_tolerance$bootstrapInterval,
    info = "percentile bootstrap upper bound"
  )
  expect_equal(
    unname(indirect$standardError), golden$bootSE,
    tolerance = process_tolerance$bootstrapSE,
    info = "percentile bootstrap standard error"
  )
})

test_that("model_4 bias-corrected bootstrap intervals match official macro", {
  work <- tempfile(pattern = "rp-process-bcb-")
  dir.create(work)
  data_path <- file.path(work, "data.csv")
  write_golden_data(data_path)
  spec <- make_process_spec(4)
  spec$estimation$bootstrap$enabled <- TRUE
  spec$estimation$bootstrap$replicates <- 5000
  spec$estimation$bootstrap$method <- "bias_corrected"
  spec$estimation$bootstrap$seed <- 20260730
  result <- run_process_runner(spec, data_path, work)

  golden <- golden_indirect("model_4", "indirectBiasCorrected")[[1]]
  indirect <- Filter(function(effect) effect$type == "indirect", result$effects)[[1]]
  interval <- indirect$confidenceInterval
  expect_equal(
    interval$lower, golden$bootLLCI,
    tolerance = process_tolerance$bootstrapInterval,
    info = "bias-corrected lower bound"
  )
  expect_equal(
    interval$upper, golden$bootULCI,
    tolerance = process_tolerance$bootstrapInterval,
    info = "bias-corrected upper bound"
  )
})

test_that("model_7 conditional effects and index match official macro", {
  work <- tempfile(pattern = "rp-process-m7-")
  dir.create(work)
  data_path <- file.path(work, "data.csv")
  write_golden_data(data_path)
  spec <- make_process_spec(7)
  spec$estimation$bootstrap$enabled <- TRUE
  spec$estimation$bootstrap$replicates <- 5000
  spec$estimation$bootstrap$method <- "percentile"
  spec$estimation$bootstrap$seed <- 20260730
  result <- run_process_runner(spec, data_path, work)

  actual <- process_equation_coeffs(result)
  expect_coefficients_match(
    actual[["m1"]], process_golden_models[["model_7"]]$equations[[1]],
    "model_7", process_tolerance$coefficient
  )
  expect_coefficients_match(
    actual[["y"]], process_golden_models[["model_7"]]$equations[[2]],
    "model_7", process_tolerance$coefficient
  )

  golden_conditional <- golden_indirect("model_7", "conditional")
  conditional <- Filter(function(effect) effect$type == "conditional", result$effects)
  expect_length(conditional, length(golden_conditional))
  for (index in seq_along(golden_conditional)) {
    expect_equal(
      unname(conditional[[index]]$estimate), golden_conditional[[index]]$effect,
      tolerance = process_tolerance$effect,
      info = paste0("conditional effect ", index)
    )
  }

  golden_index <- golden_indirect("model_7", "index")[[1]]
  index_effect <- Filter(
    function(effect) effect$type == "index",
    result$effects
  )[[1]]
  expect_equal(
    unname(index_effect$estimate), golden_index$effect,
    tolerance = process_tolerance$effect,
    info = "index of moderated mediation"
  )
})

test_that("model_1 JN grid matches official macro", {
  work <- tempfile(pattern = "rp-process-jn-")
  dir.create(work)
  data_path <- file.path(work, "data.csv")
  write_golden_data(data_path)
  spec <- make_process_spec(1)
  result <- run_process_runner(spec, data_path, work)

  # The macro reports a 21-row probe grid; the runner reports a 101-row grid.
  # Compare the conditional effect at each official probe W value via the
  # nearest runner grid point (grid spacing ~0.04 on the observed range).
  # The macro probes W on the centered scale; the runner reports moderator
  # values on the original scale. Convert official probes back to original
  # scale before matching against the runner grid.
  row <- 1:240
  w_original <- cos(row * 0.23) + sin(row * 0.07)
  w_mean <- mean(w_original)
  golden_grid <- process_golden_models[["model_1"]]$jn$grid
  jn <- result$johnsonNeyman
  expect_false(is.null(jn), info = "runner must report a JN grid for model 1")
  grid <- jn$grid
  nearest_effect <- function(probe_w) {
    distances <- vapply(grid, function(row) abs(row$moderatorValue - probe_w), numeric(1))
    grid[[which.min(distances)]]$effect
  }
  for (index in seq_along(golden_grid)) {
    original_w <- golden_grid[[index]]$w + w_mean
    expect_equal(
      nearest_effect(original_w), golden_grid[[index]]$effect,
      tolerance = 0.005,
      info = paste0("JN grid effect at W=", golden_grid[[index]]$w)
    )
  }
})

test_that("model_6 serial mediation effects match official macro", {
  work <- tempfile(pattern = "rp-process-m6-")
  dir.create(work)
  data_path <- file.path(work, "data.csv")
  write_golden_data(data_path)
  spec <- make_process_spec(6)
  spec$estimation$bootstrap$enabled <- TRUE
  spec$estimation$bootstrap$replicates <- 5000
  spec$estimation$bootstrap$method <- "percentile"
  spec$estimation$bootstrap$seed <- 20260730
  result <- run_process_runner(spec, data_path, work)

  actual <- process_equation_coeffs(result)
  expect_coefficients_match(
    actual[["m1"]], process_golden_models[["model_6"]]$equations[[1]],
    "model_6", process_tolerance$coefficient
  )
  expect_coefficients_match(
    actual[["m2"]], process_golden_models[["model_6"]]$equations[[2]],
    "model_6", process_tolerance$coefficient
  )
  expect_coefficients_match(
    actual[["y"]], process_golden_models[["model_6"]]$equations[[3]],
    "model_6", process_tolerance$coefficient
  )

  golden <- golden_indirect("model_6")
  indirect_by_id <- stats::setNames(
    Filter(function(effect) effect$type == "indirect", result$effects),
    vapply(
      Filter(function(effect) effect$type == "indirect", result$effects),
      function(effect) effect$id,
      character(1)
    )
  )
  # Official rows are ordered TOTAL, Ind1, Ind2, Ind3; runner ids are
  # effect_indirect_1/2/3 and effect_total_indirect. Match by semantics.
  golden_by_label <- stats::setNames(golden, vapply(golden, function(row) row$label, character(1)))
  mapping <- list(
    "TOTAL" = "effect_total_indirect",
    "Ind1" = "effect_indirect_1",
    "Ind2" = "effect_indirect_2",
    "Ind3" = "effect_indirect_3"
  )
  for (official_label in names(mapping)) {
    golden_row <- golden_by_label[[official_label]]
    effect <- indirect_by_id[[mapping[[official_label]]]]
    expect_equal(
      unname(effect$estimate), golden_row$effect,
      tolerance = process_tolerance$effect,
      info = paste0("model_6 indirect effect ", official_label)
    )
    interval <- effect$confidenceInterval
    expect_equal(
      interval$lower, golden_row$bootLLCI,
      tolerance = process_tolerance$bootstrapInterval,
      info = paste0("model_6 lower bound ", official_label)
    )
    expect_equal(
      interval$upper, golden_row$bootULCI,
      tolerance = process_tolerance$bootstrapInterval,
      info = paste0("model_6 upper bound ", official_label)
    )
  }
})

test_that("model_14 conditional effects and index match official macro", {
  work <- tempfile(pattern = "rp-process-m14-")
  dir.create(work)
  data_path <- file.path(work, "data.csv")
  write_golden_data(data_path)
  spec <- make_process_spec(14)
  spec$estimation$bootstrap$enabled <- TRUE
  spec$estimation$bootstrap$replicates <- 5000
  spec$estimation$bootstrap$method <- "percentile"
  spec$estimation$bootstrap$seed <- 20260730
  result <- run_process_runner(spec, data_path, work)

  actual <- process_equation_coeffs(result)
  expect_coefficients_match(
    actual[["m1"]], process_golden_models[["model_14"]]$equations[[1]],
    "model_14", process_tolerance$coefficient
  )
  expect_coefficients_match(
    actual[["y"]], process_golden_models[["model_14"]]$equations[[2]],
    "model_14", process_tolerance$coefficient
  )

  golden_conditional <- golden_indirect("model_14", "conditional")
  conditional <- Filter(function(effect) effect$type == "conditional", result$effects)
  expect_length(conditional, length(golden_conditional))
  for (index in seq_along(golden_conditional)) {
    expect_equal(
      unname(conditional[[index]]$estimate), golden_conditional[[index]]$effect,
      tolerance = process_tolerance$effect,
      info = paste0("model_14 conditional effect ", index)
    )
  }

  golden_index <- golden_indirect("model_14", "index")[[1]]
  index_effect <- Filter(function(effect) effect$type == "index", result$effects)[[1]]
  expect_equal(
    unname(index_effect$estimate), golden_index$effect,
    tolerance = process_tolerance$effect,
    info = "model_14 index of moderated mediation"
  )
})
