# Public-data oracle tests: product PROCESS runner vs the OFFICIAL PROCESS 5.0
# macro on Hayes (2022) book datasets.
#
# The frozen oracle lives in engine/R/tests/reference/public-data-oracle.json
# (generated by the official macro, never by the product runner) and the
# public datasets live outside the tracked tree under
# output/validation-datasets (see REFERENCE.md there). When the datasets are
# absent (e.g. CI without the validation bundle) every test skips; when they
# are present the engine must reproduce the oracle within frozen tolerances.
#
# Engine specs mirror the official SPSS code.sps verbatim: same model number,
# same variables/covariates, same bootstrap seed, and NO centering (the
# official macro runs center=0; the engine spec omits mean centering).

public_data_dir <- Sys.getenv(
  "RESEARCHPATH_PUBLIC_DATA_DIR",
  file.path(Sys.getenv("RESEARCHPATH_PROJECT_ROOT"), "output", "validation-datasets")
)
oracle_path <- file.path(
  Sys.getenv("RESEARCHPATH_PROJECT_ROOT"),
  "engine", "R", "tests", "reference", "public-data-oracle.json"
)
hayes_dir <- file.path(public_data_dir, "hayes", "hayes2022data")

public_oracle <- if (file.exists(oracle_path)) {
  jsonlite::fromJSON(oracle_path, simplifyVector = FALSE)
} else {
  NULL
}
public_tolerance <- public_oracle$provenance$tolerance
public_runs <- public_oracle$runs

nd <- function(id, var, role, type = "continuous") {
  list(id = id, variableId = var, label = id, kind = "observed", role = role, dataType = type)
}
edge <- function(from, to) list(id = paste0("edge_", from, "_", to), from = from, to = to, kind = "regression")
mod <- function(target_edge_id, moderator_id, id = "mod_0", product_term_id = "int_1",
                secondary_moderator_id = NULL, moderator_product_term_id = NULL) {
  entry <- list(id = id, moderatorNodeId = moderator_id, targetEdgeId = target_edge_id,
                productTermId = product_term_id)
  if (!is.null(secondary_moderator_id)) entry$secondaryModeratorNodeId <- secondary_moderator_id
  if (!is.null(moderator_product_term_id)) entry$moderatorProductTermId <- moderator_product_term_id
  entry
}
cov <- function(node_id, outcomes) list(nodeId = node_id, outcomeNodeIds = as.list(outcomes))

estimation_block <- function(bootstrap_enabled, seed) {
  list(
    family = "ols",
    standardErrors = "classical",
    confidenceLevel = 0.95,
    bootstrap = list(
      enabled = bootstrap_enabled, replicates = 5000,
      method = "percentile", seed = seed
    ),
    missing = "complete_cases_per_model",
    centering = list(method = "none", nodeIds = list()),
    reportScale = "unstandardized_primary"
  )
}

base_spec <- function(nodes, edges, moderations = list(), covariates = list(), estimation) {
  list(
    schemaVersion = "1.0.0",
    modelId = "public_data_validation",
    name = "public data oracle validation",
    datasetVersionId = "public_oracle",
    design = list(timeStructure = "cross_sectional", clustering = "none", claimMode = "associational"),
    nodes = nodes,
    edges = edges,
    moderations = moderations,
    covariates = covariates,
    estimation = estimation
  )
}

spec_for <- function(tag) {
  switch(tag,
    pmi_m4 = base_spec(
      nodes = list(nd("x", "cond", "x", "binary"), nd("m1", "pmi", "m"), nd("y", "reaction", "y")),
      edges = list(edge("x", "m1"), edge("m1", "y"), edge("x", "y")),
      estimation = estimation_block(TRUE, 31216)
    ),
    pmi_m6_serial = base_spec(
      nodes = list(
        nd("x", "cond", "x", "binary"), nd("m1", "import", "m"),
        nd("m2", "pmi", "m"), nd("y", "reaction", "y")
      ),
      edges = list(
        edge("x", "m1"), edge("x", "m2"), edge("m1", "m2"),
        edge("m1", "y"), edge("m2", "y"), edge("x", "y")
      ),
      estimation = estimation_block(TRUE, 31216)
    ),
    estress_m4_cov = base_spec(
      nodes = list(
        nd("x", "estress", "x"), nd("m1", "affect", "m"), nd("y", "withdraw", "y"),
        nd("c_ese", "ese", "covariate"), nd("c_sex", "sex", "covariate"),
        nd("c_tenure", "tenure", "covariate")
      ),
      edges = list(edge("x", "m1"), edge("m1", "y"), edge("x", "y")),
      covariates = list(
        cov("c_ese", c("m1", "y")), cov("c_sex", c("m1", "y")), cov("c_tenure", c("m1", "y"))
      ),
      estimation = estimation_block(TRUE, 100770)
    ),
    disaster_m1_jn = base_spec(
      nodes = list(nd("x", "frame", "x", "binary"), nd("w", "skeptic", "w"), nd("y", "justify", "y")),
      edges = list(edge("x", "y")),
      moderations = list(mod("edge_x_y", "w")),
      estimation = estimation_block(FALSE, 280417)
    ),
    glbwarm_m1_jn = base_spec(
      nodes = list(
        nd("x", "negemot", "x"), nd("w", "age", "w"), nd("y", "govact", "y"),
        nd("c_posemot", "posemot", "covariate"),
        nd("c_ideology", "ideology", "covariate"),
        nd("c_sex", "sex", "covariate")
      ),
      edges = list(edge("x", "y")),
      moderations = list(mod("edge_x_y", "w")),
      covariates = list(
        cov("c_posemot", "y"), cov("c_ideology", "y"), cov("c_sex", "y")
      ),
      estimation = estimation_block(FALSE, 280417)
    ),
    glbwarm_m2 = base_spec(
      nodes = list(
        nd("x", "negemot", "x"), nd("w", "sex", "w"), nd("z", "age", "z"),
        nd("y", "govact", "y"),
        nd("c_posemot", "posemot", "covariate"),
        nd("c_ideology", "ideology", "covariate")
      ),
      edges = list(edge("x", "y")),
      moderations = list(
        mod("edge_x_y", "w", "mod_0", "int_1"),
        mod("edge_x_y", "z", "mod_1", "int_2")
      ),
      covariates = list(cov("c_posemot", "y"), cov("c_ideology", "y")),
      estimation = estimation_block(FALSE, 280417)
    ),
    glbwarm_m3_jn = base_spec(
      nodes = list(
        nd("x", "negemot", "x"), nd("w", "sex", "w"), nd("z", "age", "z"),
        nd("y", "govact", "y"),
        nd("c_posemot", "posemot", "covariate"),
        nd("c_ideology", "ideology", "covariate")
      ),
      edges = list(edge("x", "y")),
      moderations = list(
        mod("edge_x_y", "w", "mod_0", "int_1"),
        mod("edge_x_y", "z", "mod_1", "int_2"),
        mod("edge_x_y", "w", "mod_2", "int_4",
            secondary_moderator_id = "z", moderator_product_term_id = "int_3")
      ),
      covariates = list(cov("c_posemot", "y"), cov("c_ideology", "y")),
      estimation = estimation_block(FALSE, 280417)
    ),
    disaster_m8 = base_spec(
      nodes = list(
        nd("x", "frame", "x", "binary"), nd("m1", "justify", "m"),
        nd("w", "skeptic", "w"), nd("y", "donate", "y")
      ),
      edges = list(edge("x", "m1"), edge("m1", "y"), edge("x", "y")),
      moderations = list(
        mod("edge_x_m1", "w", "mod_0", "int_1"),
        mod("edge_x_y", "w", "mod_1", "int_1")
      ),
      estimation = estimation_block(TRUE, 280417)
    ),
    disaster_m4 = base_spec(
      nodes = list(
        nd("x", "frame", "x", "binary"), nd("m1", "justify", "m"),
        nd("y", "donate", "y")
      ),
      edges = list(edge("x", "m1"), edge("m1", "y"), edge("x", "y")),
      estimation = estimation_block(TRUE, 280417)
    ),
    disaster_m7 = base_spec(
      nodes = list(
        nd("x", "frame", "x", "binary"), nd("m1", "justify", "m"),
        nd("w", "skeptic", "w"), nd("y", "donate", "y"),
        nd("c_skeptic", "skeptic", "covariate")
      ),
      edges = list(edge("x", "m1"), edge("m1", "y"), edge("x", "y")),
      moderations = list(mod("edge_x_m1", "w", "mod_0", "int_1")),
      covariates = list(cov("c_skeptic", "y")),
      estimation = estimation_block(TRUE, 280417)
    ),
    teams_m14 = base_spec(
      nodes = list(
        nd("x", "dysfunc", "x"), nd("m1", "negtone", "m"),
        nd("w", "negexp", "w"), nd("y", "perform", "y")
      ),
      edges = list(edge("x", "m1"), edge("m1", "y"), edge("x", "y")),
      moderations = list(mod("edge_m1_y", "w")),
      estimation = estimation_block(TRUE, 42517)
    ),
    caskets_m1 = base_spec(
      nodes = list(nd("x", "policyc", "x"), nd("w", "kerryc", "w"), nd("y", "interest", "y")),
      edges = list(edge("x", "y")),
      moderations = list(mod("edge_x_y", "w")),
      estimation = estimation_block(FALSE, 280417)
    ),
    stop("unknown tag: ", tag)
  )
}

dataset_csv <- function(dataset, work_dir) {
  if (identical(dataset, "caskets")) {
    raw <- read.csv(
      file.path(hayes_dir, "caskets", "caskets.csv"),
      check.names = FALSE, fileEncoding = "UTF-8"
    )
    raw$policyc <- raw$policy - 0.5
    raw$kerryc <- raw$kerry - 0.5
    path <- file.path(work_dir, "caskets-centered.csv")
    write.csv(raw, path, row.names = FALSE)
    return(path)
  }
  file.path(hayes_dir, dataset, paste0(dataset, ".csv"))
}

run_engine <- function(tag, spec, data_path, work_dir) {
  input_path <- file.path(work_dir, "input.json")
  output_path <- file.path(work_dir, "output.json")
  writeLines(
    jsonlite::toJSON(
      list(
        modelSpec = spec,
        dataPath = data_path,
        progressPath = file.path(work_dir, "progress.json"),
        cancelPath = file.path(work_dir, "cancel.json"),
        processModelNumber = public_runs[[tag]]$model
      ),
      auto_unbox = TRUE, digits = NA
    ),
    input_path
  )
  runner <- file.path(
    Sys.getenv("RESEARCHPATH_PROJECT_ROOT"), "engine", "R", "run_analysis.R"
  )
  rscript <- file.path(R.home("bin"), "Rscript.exe")
  status <- system2(
    rscript, c("--vanilla", shQuote(runner), shQuote(input_path), shQuote(output_path)),
    stdout = TRUE, stderr = TRUE
  )
  if (!file.exists(output_path)) {
    stop("run_analysis.R failed for ", tag, ": ", paste(status, collapse = "\n"))
  }
  jsonlite::fromJSON(output_path, simplifyVector = FALSE)
}

node_var_map <- function(spec) {
  stats::setNames(
    vapply(spec$nodes, function(node) node$variableId, character(1)),
    vapply(spec$nodes, function(node) node$id, character(1))
  )
}

engine_equation_coeffs <- function(result) {
  stats::setNames(
    lapply(result$equations, function(equation) {
      stats::setNames(
        vapply(equation$coefficients, function(coeff) coeff$estimate, numeric(1)),
        vapply(equation$coefficients, function(coeff) coeff$term, character(1))
      )
    }),
    vapply(result$equations, function(equation) {
      trimws(strsplit(equation$formula, "~", fixed = TRUE)[[1]][1])
    }, character(1))
  )
}

# Oracle equation tables are keyed by outcome variable name; engine equations
# by node id.  Oracle terms use variable names plus the frozen product id.
check_equations <- function(tag, spec, result) {
  actual <- engine_equation_coeffs(result)
  var_by_id <- node_var_map(spec)
  oracle_equations <- public_runs[[tag]]$equations
  for (node in spec$nodes) {
    if (!node$role %in% c("m", "y")) next
    oracle_key <- node$variableId
    oracle_rows <- oracle_equations[[oracle_key]]
    if (is.null(oracle_rows)) stop("oracle missing outcome ", oracle_key, " for ", tag)
    engine_rows <- actual[[node$id]]
    if (is.null(engine_rows)) stop("engine missing outcome ", node$id, " for ", tag)
    for (row in oracle_rows) {
      term <- row$term
      candidates <- if (grepl("^int_[0-9]+$", term)) {
        term
      } else if (identical(term, "constant")) {
        "(Intercept)"
      } else {
        names(var_by_id)[var_by_id == term]
      }
      # The same variableId can back both a moderation node and a covariate
      # node (e.g. disaster_m7: skeptic as W and as covariate). Resolve
      # against the terms actually present in THIS equation first.
      present <- candidates[candidates %in% names(engine_rows)]
      engine_term <- if (length(present) > 0) present[[1]] else if (length(candidates) > 0) candidates[[1]] else term
      expect_true(
        engine_term %in% names(engine_rows),
        info = paste0(tag, ": term ", term, " missing from engine equation for ", oracle_key)
      )
      expect_equal(
        unname(engine_rows[[engine_term]]), row$coeff,
        tolerance = public_tolerance$coefficient,
        info = paste0(tag, ": coefficient ", term, " in ", oracle_key)
      )
    }
  }
}

skip_unless_public_data <- function(dataset) {
  skip_if(
    !dir.exists(hayes_dir) || !file.exists(file.path(hayes_dir, dataset, paste0(dataset, ".csv"))),
    paste0("public validation data absent for ", dataset)
  )
}

# --- Simple mediation, official seed 31216 ----------------------------------

test_that("pmi model 4 reproduces the official macro on Hayes' pmi data", {
  skip_unless_public_data("pmi")
  work <- tempfile("rp-public-pmi4-"); dir.create(work)
  spec <- spec_for("pmi_m4")
  result <- run_engine("pmi_m4", spec, dataset_csv("pmi", work), work)
  check_equations("pmi_m4", spec, result)

  oracle_effects <- public_runs$pmi_m4$effects
  indirect <- Filter(function(effect) effect$type == "indirect", result$effects)[[1]]
  direct <- Filter(function(effect) effect$type == "direct", result$effects)[[1]]
  golden_indirect <- oracle_effects$indirect[[1]]
  expect_equal(unname(indirect$estimate), golden_indirect$effect,
    tolerance = public_tolerance$effect, info = "pmi_m4 indirect effect")
  expect_equal(unname(indirect$standardError), golden_indirect$bootSE,
    tolerance = public_tolerance$bootstrapSE, info = "pmi_m4 indirect bootSE")
  interval <- indirect$confidenceInterval
  expect_equal(interval$lower, golden_indirect$bootLLCI,
    tolerance = public_tolerance$bootstrapInterval, info = "pmi_m4 indirect lower")
  expect_equal(interval$upper, golden_indirect$bootULCI,
    tolerance = public_tolerance$bootstrapInterval, info = "pmi_m4 indirect upper")
  expect_equal(unname(direct$estimate), oracle_effects$direct$effect,
    tolerance = public_tolerance$effect, info = "pmi_m4 direct effect")
})

# --- Serial mediation, official seed 31216 ----------------------------------

test_that("pmi model 6 serial mediation matches the official macro", {
  skip_unless_public_data("pmi")
  work <- tempfile("rp-public-pmi6-"); dir.create(work)
  spec <- spec_for("pmi_m6_serial")
  result <- run_engine("pmi_m6_serial", spec, dataset_csv("pmi", work), work)
  check_equations("pmi_m6_serial", spec, result)

  golden <- public_runs$pmi_m6_serial$effects$indirect
  indirect_by_id <- stats::setNames(
    Filter(function(effect) effect$type == "indirect", result$effects),
    vapply(Filter(function(effect) effect$type == "indirect", result$effects),
      function(effect) effect$id, character(1))
  )
  golden_by_label <- stats::setNames(golden, vapply(golden, function(row) row$label, character(1)))
  mapping <- list(
    "TOTAL" = "effect_total_indirect",
    "Ind1" = "effect_indirect_1",
    "Ind2" = "effect_indirect_2",
    "Ind3" = "effect_indirect_3"
  )
  for (official_label in names(mapping)) {
    golden_row <- golden_by_label[[official_label]]
    effect <- indirect_by_id[[mapping[[official_label]]]]
    expect_equal(unname(effect$estimate), golden_row$effect,
      tolerance = public_tolerance$effect, info = paste0("pmi_m6 ", official_label, " effect"))
    interval <- effect$confidenceInterval
    expect_equal(interval$lower, golden_row$bootLLCI,
      tolerance = public_tolerance$bootstrapInterval, info = paste0("pmi_m6 ", official_label, " lower"))
    expect_equal(interval$upper, golden_row$bootULCI,
      tolerance = public_tolerance$bootstrapInterval, info = paste0("pmi_m6 ", official_label, " upper"))
  }
})

# --- Mediation with covariates, official seed 100770 -------------------------

test_that("estress model 4 with covariates matches the official macro", {
  skip_unless_public_data("estress")
  work <- tempfile("rp-public-estress-"); dir.create(work)
  spec <- spec_for("estress_m4_cov")
  result <- run_engine("estress_m4_cov", spec, dataset_csv("estress", work), work)
  check_equations("estress_m4_cov", spec, result)

  golden <- public_runs$estress_m4_cov$effects
  indirect <- Filter(function(effect) effect$type == "indirect", result$effects)[[1]]
  direct <- Filter(function(effect) effect$type == "direct", result$effects)[[1]]
  golden_indirect <- golden$indirect[[1]]
  expect_equal(unname(indirect$estimate), golden_indirect$effect,
    tolerance = public_tolerance$effect, info = "estress indirect effect")
  interval <- indirect$confidenceInterval
  expect_equal(interval$lower, golden_indirect$bootLLCI,
    tolerance = public_tolerance$bootstrapInterval, info = "estress indirect lower")
  expect_equal(interval$upper, golden_indirect$bootULCI,
    tolerance = public_tolerance$bootstrapInterval, info = "estress indirect upper")
  expect_equal(unname(direct$estimate), golden$direct$effect,
    tolerance = public_tolerance$effect, info = "estress direct effect")
})

# --- Model 14 moderated mediation, official seed 42517 ------------------------

test_that("teams model 14 conditional indirect effects and index match the official macro", {
  skip_unless_public_data("teams")
  work <- tempfile("rp-public-teams-"); dir.create(work)
  spec <- spec_for("teams_m14")
  result <- run_engine("teams_m14", spec, dataset_csv("teams", work), work)
  check_equations("teams_m14", spec, result)

  golden_conditional <- public_runs$teams_m14$conditionalIndirect
  conditional <- Filter(function(effect) effect$type == "conditional", result$effects)
  expect_length(conditional, length(golden_conditional))
  for (index in seq_along(golden_conditional)) {
    row <- golden_conditional[[index]]
    # engine rows are ordered by the same 16/50/84 percentile probes
    matched <- conditional[[index]]
    expect_equal(unname(matched$estimate), row$effect,
      tolerance = public_tolerance$effect, info = paste0("teams conditional indirect ", index))
    interval <- matched$confidenceInterval
    expect_equal(interval$lower, row$bootLLCI,
      tolerance = public_tolerance$bootstrapInterval, info = paste0("teams conditional lower ", index))
    expect_equal(interval$upper, row$bootULCI,
      tolerance = public_tolerance$bootstrapInterval, info = paste0("teams conditional upper ", index))
  }
  golden_index <- public_runs$teams_m14$index
  index_effect <- Filter(function(effect) effect$type == "index", result$effects)[[1]]
  expect_equal(unname(index_effect$estimate), golden_index$index,
    tolerance = public_tolerance$effect, info = "teams index of moderated mediation")
})

# --- Model 1 moderation: full conditional-effect surface via JN grid ----------

jn_surface_check <- function(tag, spec, result) {
  # The engine reports a 101-row JN grid; compare the whole conditional-effect
  # surface against the oracle's frozen equation coefficients (exact linear
  # identity) instead of tolerating grid-position mismatch.
  var_by_id <- node_var_map(spec)
  oracle_equation <- public_runs[[tag]]$equations[[
    names(public_runs[[tag]]$equations)[1]
  ]]
  oracle_coeff <- function(term) {
    row <- Filter(function(r) identical(r$term, term), oracle_equation)[[1]]
    if (is.null(row)) return(0)
    row$coeff
  }
  b_x <- oracle_coeff(var_by_id[["x"]])
  b_int <- oracle_coeff("int_1")
  grid <- result$johnsonNeyman$grid
  expect_false(is.null(grid), info = paste0(tag, ": runner must report a JN grid"))
  for (row in grid) {
    expected <- b_x + b_int * row$moderatorValue
    # The official macro prints coefficients to 4 decimals; the frozen oracle
    # therefore carries at most +/-0.00005 rounding per coefficient. The bound
    # below is the propagated rounding error, not a statistical tolerance.
    rounding_bound <- 5e-5 * (1 + abs(row$moderatorValue)) + 1e-6
    expect_equal(
      unname(row$effect), expected,
      tolerance = rounding_bound,
      info = paste0(tag, ": JN grid effect at W=", row$moderatorValue)
    )
  }
  invisible(TRUE)
}

test_that("disaster model 1 JN surface matches the official macro coefficients", {
  skip_unless_public_data("disaster")
  work <- tempfile("rp-public-disaster-"); dir.create(work)
  spec <- spec_for("disaster_m1_jn")
  result <- run_engine("disaster_m1_jn", spec, dataset_csv("disaster", work), work)
  check_equations("disaster_m1_jn", spec, result)
  jn_surface_check("disaster_m1_jn", spec, result)
})

test_that("glbwarm model 1 with covariates JN surface matches the official macro", {
  skip_unless_public_data("glbwarm")
  work <- tempfile("rp-public-glbwarm-"); dir.create(work)
  spec <- spec_for("glbwarm_m1_jn")
  result <- run_engine("glbwarm_m1_jn", spec, dataset_csv("glbwarm", work), work)
  check_equations("glbwarm_m1_jn", spec, result)
  jn_surface_check("glbwarm_m1_jn", spec, result)
})

# --- Model 2/3: multi-moderator moderation with covariates ---------------------

test_that("glbwarm model 2 (W+Z moderation) coefficients match the official macro", {
  skip_unless_public_data("glbwarm")
  work <- tempfile("rp-public-glbwarm2-"); dir.create(work)
  spec <- spec_for("glbwarm_m2")
  result <- run_engine("glbwarm_m2", spec, dataset_csv("glbwarm", work), work)
  check_equations("glbwarm_m2", spec, result)
})

test_that("glbwarm model 3 (three-way interaction) coefficients match the official macro", {
  skip_unless_public_data("glbwarm")
  work <- tempfile("rp-public-glbwarm3-"); dir.create(work)
  spec <- spec_for("glbwarm_m3_jn")
  result <- run_engine("glbwarm_m3_jn", spec, dataset_csv("glbwarm", work), work)
  check_equations("glbwarm_m3_jn", spec, result)
})

# --- Model 8: moderated mediation (a and direct paths moderated) ---------------

test_that("disaster model 8 conditional indirect effects and index match the official macro", {
  skip_unless_public_data("disaster")
  work <- tempfile("rp-public-disaster8-"); dir.create(work)
  spec <- spec_for("disaster_m8")
  result <- run_engine("disaster_m8", spec, dataset_csv("disaster", work), work)
  check_equations("disaster_m8", spec, result)

  golden_conditional <- public_runs$disaster_m8$conditionalIndirect
  conditional <- Filter(function(effect) effect$type == "conditional", result$effects)
  expect_length(conditional, length(golden_conditional))
  for (index in seq_along(golden_conditional)) {
    row <- golden_conditional[[index]]
    matched <- conditional[[index]]
    expect_equal(unname(matched$estimate), row$effect,
      tolerance = public_tolerance$effect, info = paste0("disaster_m8 conditional indirect ", index))
    interval <- matched$confidenceInterval
    expect_equal(interval$lower, row$bootLLCI,
      tolerance = public_tolerance$bootstrapInterval, info = paste0("disaster_m8 conditional lower ", index))
    expect_equal(interval$upper, row$bootULCI,
      tolerance = public_tolerance$bootstrapInterval, info = paste0("disaster_m8 conditional upper ", index))
  }
  golden_index <- public_runs$disaster_m8$index
  index_effect <- Filter(function(effect) effect$type == "index", result$effects)[[1]]
  expect_equal(unname(index_effect$estimate), golden_index$index,
    tolerance = public_tolerance$effect, info = "disaster_m8 index of moderated mediation")
})

test_that("disaster model 4 mediation matches the official macro", {
  skip_unless_public_data("disaster")
  work <- tempfile("rp-public-disaster4-"); dir.create(work)
  spec <- spec_for("disaster_m4")
  result <- run_engine("disaster_m4", spec, dataset_csv("disaster", work), work)
  check_equations("disaster_m4", spec, result)

  golden <- public_runs$disaster_m4$effects
  indirect <- Filter(function(effect) effect$type == "indirect", result$effects)[[1]]
  direct <- Filter(function(effect) effect$type == "direct", result$effects)[[1]]
  golden_indirect <- golden$indirect[[1]]
  expect_equal(unname(indirect$estimate), golden_indirect$effect,
    tolerance = public_tolerance$effect, info = "disaster_m4 indirect effect")
  interval <- indirect$confidenceInterval
  expect_equal(interval$lower, golden_indirect$bootLLCI,
    tolerance = public_tolerance$bootstrapInterval, info = "disaster_m4 indirect lower")
  expect_equal(interval$upper, golden_indirect$bootULCI,
    tolerance = public_tolerance$bootstrapInterval, info = "disaster_m4 indirect upper")
  expect_equal(unname(direct$estimate), golden$direct$effect,
    tolerance = public_tolerance$effect, info = "disaster_m4 direct effect")
})

test_that("disaster model 7 moderated mediation matches the official macro", {
  skip_unless_public_data("disaster")
  work <- tempfile("rp-public-disaster7-"); dir.create(work)
  spec <- spec_for("disaster_m7")
  result <- run_engine("disaster_m7", spec, dataset_csv("disaster", work), work)
  check_equations("disaster_m7", spec, result)

  golden_conditional <- public_runs$disaster_m7$conditionalIndirect
  conditional <- Filter(function(effect) effect$type == "conditional", result$effects)
  expect_length(conditional, length(golden_conditional))
  for (index in seq_along(golden_conditional)) {
    row <- golden_conditional[[index]]
    matched <- conditional[[index]]
    expect_equal(unname(matched$estimate), row$effect,
      tolerance = public_tolerance$effect, info = paste0("disaster_m7 conditional indirect ", index))
    interval <- matched$confidenceInterval
    expect_equal(interval$lower, row$bootLLCI,
      tolerance = public_tolerance$bootstrapInterval, info = paste0("disaster_m7 conditional lower ", index))
    expect_equal(interval$upper, row$bootULCI,
      tolerance = public_tolerance$bootstrapInterval, info = paste0("disaster_m7 conditional upper ", index))
  }
  golden_index <- public_runs$disaster_m7$index
  index_effect <- Filter(function(effect) effect$type == "index", result$effects)[[1]]
  expect_equal(unname(index_effect$estimate), golden_index$index,
    tolerance = public_tolerance$effect, info = "disaster_m7 index of moderated mediation")
})

# --- caskets model 1 with 0.5-centered binary policy/kerry --------------------

test_that("caskets model 1 coefficients match the official macro (0.5-centered)", {
  skip_unless_public_data("caskets")
  work <- tempfile("rp-public-caskets-"); dir.create(work)
  spec <- spec_for("caskets_m1")
  result <- run_engine("caskets_m1", spec, dataset_csv("caskets", work), work)
  check_equations("caskets_m1", spec, result)
})

# --- Multicategorical X boundary: documented, asserted rejection ---------------

test_that("multicategorical X is rejected with the documented boundary error", {
  skip_unless_public_data("protest")
  work <- tempfile("rp-public-mcx-"); dir.create(work)
  spec <- base_spec(
    nodes = list(
      list(id = "x", variableId = "protest", label = "x", kind = "observed", role = "x",
           dataType = "nominal", encoding = list(method = "treatment")),
      nd("m1", "respappr", "m"), nd("y", "liking", "y")
    ),
    edges = list(edge("x", "m1"), edge("m1", "y"), edge("x", "y")),
    estimation = estimation_block(FALSE, 30217)
  )
  input_path <- file.path(work, "input.json")
  output_path <- file.path(work, "output.json")
  writeLines(
    jsonlite::toJSON(list(
      modelSpec = spec,
      dataPath = file.path(hayes_dir, "protest", "protest.csv"),
      progressPath = file.path(work, "progress.json"),
      cancelPath = file.path(work, "cancel.json"),
      processModelNumber = 4
    ), auto_unbox = TRUE, digits = NA),
    input_path
  )
  runner <- file.path(Sys.getenv("RESEARCHPATH_PROJECT_ROOT"), "engine", "R", "run_analysis.R")
  status <- suppressWarnings(system2(
    file.path(R.home("bin"), "Rscript.exe"),
    c("--vanilla", shQuote(runner), shQuote(input_path), shQuote(output_path)),
    stdout = TRUE, stderr = TRUE
  ))
  expect_false(file.exists(output_path), info = "multicategorical X must not produce a result bundle")
  expect_true(
    any(grepl("PROCESS variable x must be continuous or binary", status)),
    info = paste0("expected the documented boundary error; got: ", paste(status, collapse = "\n"))
  )
})
