# Golden-standard tests (part 2): legacy PROCESS templates 5/15/21/22/58/59
# against the OFFICIAL PROCESS 5.0 macro on deterministic synthetic data.
#
# Frozen values live in engine/R/tests/reference/process-goldens-2.json
# (generated by generate-process-goldens.R with the official macro; kept in a
# second file to respect the architecture line ceiling). The product runner
# never participates in golden generation.

process_goldens2 <- jsonlite::fromJSON(
  file.path(
    Sys.getenv("RESEARCHPATH_PROJECT_ROOT"),
    "engine", "R", "tests", "reference", "process-goldens-2.json"
  ),
  simplifyVector = FALSE
)
process_golden_models2 <- process_goldens2$models
process_tolerance2 <- process_goldens2$provenance$tolerance

# Third golden file: generic-estimator catalog models 28/29 (DEBT-118 residual).
process_goldens3 <- jsonlite::fromJSON(
  file.path(
    Sys.getenv("RESEARCHPATH_PROJECT_ROOT"),
    "engine", "R", "tests", "reference", "process-goldens-3.json"
  ),
  simplifyVector = FALSE
)
process_golden_models3 <- process_goldens3$models

make_process_spec2 <- function(model_number) {
  edges <- switch(
    as.character(model_number),
    "5" = list(c("x", "m1"), c("m1", "y"), c("x", "y")),
    "15" = list(c("x", "m1"), c("m1", "y"), c("x", "y")),
    "21" = list(c("x", "m1"), c("m1", "y"), c("x", "y")),
    "22" = list(c("x", "m1"), c("m1", "y"), c("x", "y")),
    "58" = list(c("x", "m1"), c("m1", "y"), c("x", "y")),
    "59" = list(c("x", "m1"), c("m1", "y"), c("x", "y")),
    "60" = list(c("x", "m1"), c("m1", "y"), c("x", "y")),
    "28" = list(c("x", "m1"), c("m1", "y"), c("x", "y")),
    "29" = list(c("x", "m1"), c("m1", "y"), c("x", "y"))
  )
  # Each entry: moderator, target edge pair, product term id. Order matches
  # the official macro's int_1/int_2 numbering within each equation.
  moderations <- switch(
    as.character(model_number),
    "5" = list(list(moderator = "w", target = c("x", "y"), product = "int_1")),
    "15" = list(
      list(moderator = "w", target = c("x", "y"), product = "int_1"),
      list(moderator = "w", target = c("m1", "y"), product = "int_2")
    ),
    "21" = list(
      list(moderator = "w", target = c("x", "m1"), product = "int_1"),
      list(moderator = "z", target = c("m1", "y"), product = "int_2")
    ),
    "22" = list(
      list(moderator = "w", target = c("x", "m1"), product = "int_1"),
      list(moderator = "z", target = c("m1", "y"), product = "int_2"),
      list(moderator = "w", target = c("x", "y"), product = "int_3")
    ),
    "58" = list(
      list(moderator = "w", target = c("x", "m1"), product = "int_1"),
      list(moderator = "w", target = c("m1", "y"), product = "int_2")
    ),
    "59" = list(
      list(moderator = "w", target = c("x", "m1"), product = "int_1"),
      list(moderator = "w", target = c("m1", "y"), product = "int_2"),
      list(moderator = "w", target = c("x", "y"), product = "int_3")
    ),
    "60" = list(
      list(moderator = "w", target = c("x", "m1"), product = "int_1"),
      list(moderator = "z", target = c("x", "m1"), product = "int_2"),
      list(moderator = "w", target = c("m1", "y"), product = "int_3")
    ),
    "28" = list(
      list(moderator = "w", target = c("x", "m1"), product = "int_1"),
      list(moderator = "z", target = c("m1", "y"), product = "int_2"),
      list(moderator = "z", target = c("x", "y"), product = "int_3")
    ),
    "29" = list(
      list(moderator = "w", target = c("x", "m1"), product = "int_1"),
      list(moderator = "z", target = c("m1", "y"), product = "int_2"),
      list(moderator = "w", target = c("x", "y"), product = "int_3"),
      list(moderator = "z", target = c("x", "y"), product = "int_4")
    )
  )
  nodes <- list(
    list(id = "x", variableId = "var_x", label = "X", kind = "observed", role = "x", dataType = "continuous"),
    list(id = "y", variableId = "var_y", label = "Y", kind = "observed", role = "y", dataType = "continuous"),
    list(id = "m1", variableId = "var_m1", label = "M1", kind = "observed", role = "m", dataType = "continuous")
  )
  needs_w <- any(vapply(moderations, function(mod) identical(mod$moderator, "w"), logical(1)))
  needs_z <- any(vapply(moderations, function(mod) identical(mod$moderator, "z"), logical(1)))
  if (needs_w) {
    nodes <- c(nodes, list(list(id = "w", variableId = "var_w", label = "W",
                                kind = "observed", role = "w", dataType = "continuous")))
  }
  if (needs_z) {
    nodes <- c(nodes, list(list(id = "z", variableId = "var_z", label = "Z",
                                kind = "observed", role = "z", dataType = "continuous")))
  }
  edge_items <- lapply(edges, function(edge) {
    list(id = paste0("edge_", edge[1], "_", edge[2]), from = edge[1], to = edge[2], kind = "regression")
  })
  edge_id_by_pair <- stats::setNames(
    vapply(edge_items, function(edge) edge$id, character(1)),
    vapply(edge_items, function(edge) paste0(edge$from, "->", edge$to), character(1))
  )
  moderation_items <- lapply(seq_along(moderations), function(index) {
    mod <- moderations[[index]]
    list(
      id = paste0("mod_", index - 1L),
      moderatorNodeId = mod$moderator,
      targetEdgeId = edge_id_by_pair[[paste0(mod$target[1], "->", mod$target[2])]],
      productTermId = mod$product
    )
  })
  node_ids <- vapply(nodes, function(node) node$id, character(1))
  centering_ids <- node_ids[node_ids != "y"]
  list(
    schemaVersion = "1.0.0",
    modelId = paste0("catalog_model_", model_number),
    name = paste0("PROCESS Model ", model_number),
    datasetVersionId = "derived_catalog",
    design = list(timeStructure = "cross_sectional", clustering = "none", claimMode = "associational"),
    nodes = nodes,
    edges = edge_items,
    moderations = moderation_items,
    covariates = list(),
    estimation = list(
      family = "ols",
      standardErrors = "classical",
      confidenceLevel = 0.95,
      bootstrap = list(enabled = TRUE, replicates = 5000, method = "percentile", seed = 20260730),
      missing = "complete_cases_per_model",
      centering = list(method = "mean", nodeIds = centering_ids),
      reportScale = "unstandardized_primary"
    )
  )
}

write_golden_data2 <- function(path) {
  row <- 1:240
  x <- sin(row * 0.37) + cos(row * 0.11)
  w <- cos(row * 0.23) + sin(row * 0.07)
  z <- sin(row * 0.19) - cos(row * 0.13)
  m1 <- 0.4 * x + 0.18 * w - 0.12 * z + sin(row * 1.31) * 0.55
  m2 <- 0.25 * m1 + 0.15 * x + 0.1 * w + cos(row * 0.71) * 0.45
  y <- 0.22 * x + 0.36 * m1 + 0.14 * w - 0.09 * z +
    0.17 * m1 * w - 0.11 * m1 * z + 0.08 * m1 * w * z +
    cos(row * 1.17) * 0.6
  data <- data.frame(var_x = x, var_m1 = m1, var_m2 = m2, var_y = y, var_w = w, var_z = z)
  write.csv(data, path, row.names = FALSE)
}

run_process_runner2 <- function(spec, data_path, work_dir, process_model_number = NULL) {
  input_path <- file.path(work_dir, "input.json")
  output_path <- file.path(work_dir, "output.json")
  payload <- list(
    modelSpec = spec,
    dataPath = data_path,
    progressPath = file.path(work_dir, "progress.json"),
    cancelPath = file.path(work_dir, "cancel.json")
  )
  if (!is.null(process_model_number)) payload$processModelNumber <- process_model_number
  writeLines(
    jsonlite::toJSON(payload, auto_unbox = TRUE, digits = NA),
    input_path
  )
  runner <- file.path(Sys.getenv("RESEARCHPATH_PROJECT_ROOT"), "engine", "R", "run_analysis.R")
  rscript <- file.path(R.home("bin"), "Rscript.exe")
  status <- system2(
    rscript, c("--vanilla", shQuote(runner), shQuote(input_path), shQuote(output_path)),
    stdout = TRUE, stderr = TRUE
  )
  if (!file.exists(output_path)) {
    stop("run_analysis.R failed: ", paste(status, collapse = "\n"))
  }
  jsonlite::fromJSON(output_path, simplifyVector = FALSE)
}

process_equation_coeffs2 <- function(result) {
  stats::setNames(
    lapply(result$equations, function(equation) {
      stats::setNames(
        vapply(equation$coefficients, function(coeff) coeff$estimate, numeric(1)),
        vapply(equation$coefficients, function(coeff) coeff$term, character(1))
      )
    }),
    vapply(result$equations, function(equation) {
      trimws(strsplit(equation$formula, "~", fixed = TRUE)[[1]][1])
    }, character(1))
  )
}

# Official macro numbers products per equation (int_1 = first product in that
# equation). The engine numbers products per moderation entry, so models 22
# and 59 (three products) need a per-equation alias map.
term_aliases <- list(
  model_22 = list(y = c(int_1 = "int_3")),
  model_59 = list(y = c(int_1 = "int_3")),
  # The official macro numbers products per equation in model-matrix bit
  # order (direct-path moderations before b-path), the engine numbers them
  # per moderation entry.
  model_28 = list(y = c(int_2 = "int_3", int_3 = "int_2")),
  model_29 = list(y = c(int_1 = "int_3", int_2 = "int_4", int_3 = "int_2"))
)

expect_coefficients_match2 <- function(actual, expected_rows, label, model_key, equation_key, tolerance) {
  aliases <- term_aliases[[model_key]][[equation_key]] %||% character(0)
  for (row in expected_rows) {
    term <- row$term
    if (term == "constant") next
    engine_term <- if (term %in% names(aliases)) unname(aliases[[term]]) else sub("^var_", "", term)
    expect_true(engine_term %in% names(actual),
      info = paste0(label, ": term ", term, " missing from engine equation (", equation_key, ")"))
    expect_equal(
      unname(actual[[engine_term]]), row$coeff,
      tolerance = tolerance,
      info = paste0(label, ": coefficient ", term, " in ", equation_key)
    )
  }
}

`%||%` <- function(a, b) if (is.null(a) || length(a) == 0) b else a

# --- assertions ---------------------------------------------------------------

assert_legacy_template <- function(model_number) {
  key <- paste0("model_", model_number)
  work <- tempfile(paste0("rp-process2-", model_number, "-"))
  dir.create(work)
  data_path <- file.path(work, "data.csv")
  write_golden_data2(data_path)
  spec <- make_process_spec2(model_number)
  result <- run_process_runner2(spec, data_path, work)
  actual <- process_equation_coeffs2(result)
  golden <- process_golden_models2[[key]]

  expect_coefficients_match2(actual[["m1"]], golden$equations[[1]], key, key, "m1",
    process_tolerance2$coefficient)
  expect_coefficients_match2(actual[["y"]], golden$equations[[2]], key, key, "y",
    process_tolerance2$coefficient)

  if (!is.null(golden[["indirect"]])) {
    indirect <- Filter(function(effect) effect$type == "indirect", result$effects)[[1]]
    golden_row <- golden[["indirect"]][[1]]
    expect_equal(unname(indirect$estimate), golden_row$effect,
      tolerance = process_tolerance2$effect, info = paste0(key, ": indirect effect"))
    interval <- indirect$confidenceInterval
    expect_equal(interval$lower, golden_row$bootLLCI,
      tolerance = process_tolerance2$bootstrapInterval, info = paste0(key, ": indirect lower"))
    expect_equal(interval$upper, golden_row$bootULCI,
      tolerance = process_tolerance2$bootstrapInterval, info = paste0(key, ": indirect upper"))
  }

  if (!is.null(golden[["conditional"]])) {
    conditional <- Filter(function(effect) effect$type == "conditional", result$effects)
    golden_conditional <- golden[["conditional"]]
    expect_true(
      length(conditional) == length(golden_conditional),
      info = paste0(key, ": conditional count (engine=", length(conditional),
        ", macro=", length(golden_conditional), ")")
    )
    for (index in seq_along(golden_conditional)) {
      expect_equal(
        unname(conditional[[index]]$estimate), golden_conditional[[index]]$effect,
        tolerance = process_tolerance2$effect,
        info = paste0(key, ": conditional effect ", index)
      )
    }
  }

  if (!is.null(golden[["index"]])) {
    index_effect <- Filter(function(effect) effect$type == "index", result$effects)[[1]]
    golden_row <- golden[["index"]][[1]]
    expect_equal(
      unname(index_effect$estimate), golden_row$effect,
      tolerance = process_tolerance2$effect,
      info = paste0(key, ": index of moderated mediation")
    )
  }
  invisible(TRUE)
}

test_that("model_5 matches official macro (direct-path moderation + mediation)", {
  assert_legacy_template(5)
})

test_that("model_15 matches official macro (b + direct moderation)", {
  assert_legacy_template(15)
})

test_that("model_21 matches official macro (W on a, Z on b, 3x3 grid)", {
  assert_legacy_template(21)
})

test_that("model_22 matches official macro (W on a + direct, Z on b)", {
  assert_legacy_template(22)
})

test_that("model_58 matches official macro (W on a + b)", {
  assert_legacy_template(58)
})

test_that("model_59 matches official macro (W on a + b + direct)", {
  assert_legacy_template(59)
})

test_that("model_60 matches official macro (generic estimator path, a-W/a-Z/b-W)", {
  key <- "model_60"
  work <- tempfile("rp-process2-60-"); dir.create(work)
  data_path <- file.path(work, "data.csv")
  write_golden_data2(data_path)
  spec <- make_process_spec2(60)
  result <- run_process_runner2(spec, data_path, work, process_model_number = 60)
  actual <- process_equation_coeffs2(result)
  golden <- process_golden_models2[[key]]

  expect_coefficients_match2(actual[["m1"]], golden$equations[[1]], key, key, "m1",
    process_tolerance2$coefficient)
  expect_coefficients_match2(actual[["y"]], golden$equations[[2]], key, key, "y",
    process_tolerance2$coefficient)

  # The generic estimator emits path-level and total-level conditional rows;
  # compare the path rows against the macro's W x Z percentile grid.
  conditional <- Filter(
    function(effect) identical(effect$type, "conditional") &&
      grepl("^effect_path_1_conditional", effect$id),
    result$effects
  )
  golden_conditional <- golden[["conditional"]]
  expect_true(
    length(conditional) == length(golden_conditional),
    info = paste0(key, ": conditional count (engine=", length(conditional),
      ", macro=", length(golden_conditional), ")")
  )
  for (index in seq_along(golden_conditional)) {
    expect_equal(
      unname(conditional[[index]]$estimate), golden_conditional[[index]]$effect,
      tolerance = process_tolerance2$effect,
      info = paste0(key, ": conditional effect ", index)
    )
  }

  direct <- Filter(function(effect) identical(effect$type, "direct"), result$effects)[[1]]
  expect_equal(
    unname(direct$estimate), golden[["direct"]][[1]]$effect,
    tolerance = process_tolerance2$effect,
    info = paste0(key, ": direct effect")
  )
})

assert_generic_grid_template <- function(model_number) {
  key <- paste0("model_", model_number)
  work <- tempfile(paste0("rp-process2-", model_number, "-")); dir.create(work)
  data_path <- file.path(work, "data.csv")
  write_golden_data2(data_path)
  spec <- make_process_spec2(model_number)
  result <- run_process_runner2(spec, data_path, work, process_model_number = model_number)
  actual <- process_equation_coeffs2(result)
  golden <- process_golden_models3[[key]]

  expect_coefficients_match2(actual[["m1"]], golden$equations[[1]], key, key, "m1",
    process_tolerance2$coefficient)
  expect_coefficients_match2(actual[["y"]], golden$equations[[2]], key, key, "y",
    process_tolerance2$coefficient)

  conditional <- Filter(
    function(effect) identical(effect$type, "conditional") &&
      grepl("^effect_path_1_conditional", effect$id),
    result$effects
  )
  golden_conditional <- golden[["conditional"]]
  expect_true(
    length(conditional) == length(golden_conditional),
    info = paste0(key, ": conditional count (engine=", length(conditional),
      ", macro=", length(golden_conditional), ")")
  )
  for (index in seq_along(golden_conditional)) {
    expect_equal(
      unname(conditional[[index]]$estimate), golden_conditional[[index]]$effect,
      tolerance = process_tolerance2$effect,
      info = paste0(key, ": conditional effect ", index)
    )
  }
  invisible(TRUE)
}

test_that("model_28 matches official macro (generic estimator, a-W/b-Z/direct-W)", {
  assert_generic_grid_template(28)
})

test_that("model_29 matches official macro (generic estimator, a-W/b-Z/direct-W+Z)", {
  assert_generic_grid_template(29)
})
