import { expect, test, type Page } from '@playwright/test'
import { openAuthenticatedPage } from './session'
import { installPageFailureMonitor } from './quality'
import path from 'node:path'

async function chooseMethod(page: Page, label: string, accept = true) {
  await page.getByRole('tab', { name: '方法目录', exact: true }).click()
  page.once('dialog', dialog => accept ? dialog.accept() : dialog.dismiss())
  await page.getByRole('button', { name: `配置${label}`, exact: true }).click()
}

async function prepare(page: Page, kind: 'panel' | 'diary' | 'sem') {
  await openAuthenticatedPage(page)
  await page.getByRole('button', { name: /分析已有数据/ }).click()
  await page.getByRole('radio', { name: kind === 'panel' ? /追踪面板/ : kind === 'diary' ? /密集追踪/ : /单次 \/ 横截面/ }).click()
  await page.getByRole('radio', { name: /观测相互独立/ }).click()
  if (kind === 'sem') {
    const confirmStructure = page.getByRole('button', { name: '确认并保存研究结构' })
    if (await confirmStructure.isVisible()) await confirmStructure.click()
    await expect(page.getByText('研究结构已保存', { exact: true })).toBeVisible()
  }
  await page.getByRole('button', { name: kind === 'panel' ? '一键导入追踪面板示例项目' : kind === 'diary' ? '一键导入密集追踪示例项目' : '一键导入经典问卷示例项目' }).click()
  if (kind !== 'sem') {
    await page.getByRole('button', { name: '运行结构画像' }).click()
    await expect(page.getByText(/本次画像：/)).toBeVisible()
    const reason = page.getByLabel('继续使用的学术理由（至少 10 个字符）')
    if (await reason.isVisible()) await reason.fill('已核查个体与时间角色，本次只验证配置入口和草稿保持。')
    await page.getByRole('button', { name: '保存结构版本' }).click()
    await expect(page.getByText('当前角色与服务端已保存的结构版本一致，可以继续进入下游工作流。')).toBeVisible()
  } else await expect(page.getByText('测量层已完成 · v1')).toBeVisible()
}

test('catalog selects SEM safely and never replays a consumed switch', async ({ page }) => {
  test.setTimeout(90_000)
  const failures = await installPageFailureMonitor(page, { classifyModelCanvasResizeLoop: true })
  await prepare(page, 'sem')
  await chooseMethod(page, '结构方程模型', false)
  await expect(page.getByText('已取消目录方法切换，原模型草稿保持不变。')).toBeVisible()
  await expect(page.getByText('估计模式：PROCESS (OLS)')).toBeVisible()
  await chooseMethod(page, '结构方程模型')
  await expect(page.locator('.react-flow__node[data-id^="indicator:"]')).toHaveCount(9)
  await page.getByRole('button', { name: '添加高阶潜变量' }).click()
  await expect(page.getByText('草稿已保存', { exact: true })).toBeVisible()
  // Reopening the same family must preserve custom measurement, without a dialog.
  await page.getByRole('tab', { name: '方法目录', exact: true }).click()
  await page.getByRole('button', { name: '配置结构方程模型', exact: true }).click()
  await expect(page.locator('.react-flow__node[data-id^="higher_factor_"]')).toHaveCount(1)
  await page.reload()
  await expect(page.locator('.react-flow__node[data-id^="higher_factor_"]')).toHaveCount(1)
  await failures.expectClean()
})

test('catalog carries CLPM, RI-CLPM and LCM-SR while cancellation preserves the saved panel draft', async ({ page }) => {
  test.setTimeout(90_000)
  const failures = await installPageFailureMonitor(page)
  await prepare(page, 'panel')
  await chooseMethod(page, '传统 CLPM')
  await expect(page.getByRole('combobox', { name: '模型', exact: true })).toHaveValue('clpm')
  await page.getByLabel('波次 1 标签').fill('我的基线')
  await chooseMethod(page, 'RI-CLPM', false)
  await expect(page.getByRole('combobox', { name: '模型', exact: true })).toHaveValue('clpm')
  await expect(page.getByLabel('波次 1 标签')).toHaveValue('我的基线')
  await page.getByRole('tab', { name: '方法目录', exact: true }).click()
  await page.getByRole('tab', { name: '统计分析', exact: true }).click()
  await expect(page.getByRole('combobox', { name: '模型', exact: true })).toHaveValue('clpm')
  await chooseMethod(page, 'RI-CLPM')
  await expect(page.getByRole('combobox', { name: '模型', exact: true })).toHaveValue('ri_clpm')
  await chooseMethod(page, 'LCM-SR')
  await expect(page.getByRole('combobox', { name: '模型', exact: true })).toHaveValue('lcm_sr')
  await expect(page.getByRole('combobox', { name: '测量模式', exact: true })).toHaveValue('latent_items')
  await expect(page.getByLabel('波次 1 标签')).toHaveValue('我的基线')
  await page.reload()
  await expect(page.getByRole('combobox', { name: '模型', exact: true })).toHaveValue('lcm_sr')
  await failures.expectClean()
})

test('catalog selects diary GLMM and mediation without discarding variable choices', async ({ page }) => {
  test.setTimeout(90_000)
  const failures = await installPageFailureMonitor(page)
  await prepare(page, 'diary')
  await chooseMethod(page, '日记/ESM GLMM')
  await expect(page.getByRole('combobox', { name: '分析类型', exact: true })).toHaveValue('glmm')
  await expect(page.getByRole('combobox', { name: '结局分布', exact: true })).toHaveValue('binomial')
  await chooseMethod(page, '日记/ESM 多层中介')
  await expect(page.getByRole('combobox', { name: '分析类型', exact: true })).toHaveValue('mediation')
  await page.reload()
  await expect(page.getByRole('combobox', { name: '分析类型', exact: true })).toHaveValue('mediation')
  await failures.expectClean()
})

test('catalog selects DSEM on an eligible 25-occasion ESM dataset and restores its custom settings', async ({ page }) => {
  test.setTimeout(120_000)
  const failures = await installPageFailureMonitor(page)
  await openAuthenticatedPage(page)
  await page.getByRole('button', { name: /分析已有数据/ }).click()
  await page.getByRole('radio', { name: /密集追踪/ }).click()
  await page.getByRole('radio', { name: /观测相互独立/ }).click()
  await page.getByLabel('选择数据文件').setInputFiles(path.resolve('samples/data/intensive-esm-demo.csv'))
  await page.getByRole('button', { name: '导入并创建数据版本' }).click()
  await expect(page.getByRole('heading', { name: '确认变量类型' })).toBeVisible()
  await page.getByLabel('person_id的最终类型').selectOption('id')
  for (const name of ['occasion', 'emotion', 'ai_trust']) await page.getByLabel(`${name}的最终类型`).selectOption('continuous')
  await page.getByRole('button', { name: '确认全部变量' }).click()
  await page.getByRole('combobox', { name: /个体 \/ 研究对象 ID/ }).selectOption({ label: 'person_id (person_id)' })
  await page.getByRole('combobox', { name: /波次 \/ 时间变量/ }).selectOption({ label: 'occasion (occasion)' })
  await page.getByRole('button', { name: '运行结构画像' }).click()
  await expect(page.getByText(/本次画像：/)).toBeVisible()
  const reason = page.getByLabel('继续使用的学术理由（至少 10 个字符）')
  if (await reason.isVisible()) await reason.fill('已核查每人二十五个测量时点，本次仅检查 DSEM 配置，不进行估计。')
  await page.getByRole('button', { name: '保存结构版本' }).click()
  const card = page.locator('.construct-card').first()
  await card.getByLabel('构念 1 名称').fill('日记测量')
  await card.getByLabel('理论最小值').fill('-10')
  await card.getByLabel('理论最大值').fill('10')
  for (const name of ['emotion', 'ai_trust']) await card.getByRole('checkbox', { name: `${name} ${name}`, exact: true }).check()
  await page.getByRole('button', { name: '保存规则并生成测量版本' }).click()
  await expect(page.getByRole('heading', { name: '日记与 ESM 分析中心', exact: true })).toBeVisible()
  await chooseMethod(page, '观测变量 Bayesian DSEM')
  await expect(page.getByRole('combobox', { name: '分析类型', exact: true })).toHaveValue('bayesian_dsem')
  await page.getByRole('spinbutton', { name: '每链迭代', exact: true }).fill('3000')
  await page.getByRole('combobox', { name: '结果变量 Y', exact: true }).selectOption({ label: 'exposure_minutes' })
  await page.getByRole('tab', { name: '方法目录', exact: true }).click()
  await page.getByRole('button', { name: '配置观测变量 Bayesian DSEM', exact: true }).click()
  await expect(page.getByRole('spinbutton', { name: '每链迭代', exact: true })).toHaveValue('3000')
  await expect(page.getByRole('combobox', { name: '结果变量 Y', exact: true }).locator('option:checked')).toHaveText('exposure_minutes')
  await page.reload()
  await expect(page.getByRole('combobox', { name: '分析类型', exact: true })).toHaveValue('bayesian_dsem')
  await expect(page.getByRole('spinbutton', { name: '每链迭代', exact: true })).toHaveValue('3000')
  await failures.expectClean()
})
