import { expect, test } from '@playwright/test'
import { configureMethod, openAdvancedSemEditor, openAnalysisLibrary, openDataWorkspace } from './session'
import { expectNoHorizontalOverflow, expectNoSeriousAccessibilityViolations, installPageFailureMonitor } from './quality'

async function startIndependent(page: Parameters<typeof openDataWorkspace>[0]) {
  await openDataWorkspace(page)
  await page.getByRole('radio', { name: /单次 \/ 横截面/ }).click()
  await page.getByRole('radio', { name: /观测相互独立/ }).click()
  await page.getByRole('radio', { name: /^观察性/ }).click()
  const confirm = page.getByRole('button', { name: '确认并保存研究结构' })
  if (await confirm.isVisible()) await confirm.click()
  await expect(page.getByText('研究结构已保存', { exact: true })).toBeVisible()
}

test('@real-r raw variables run without constructs and drafts survive navigation, refresh and active-job reconnection', async ({ page }) => {
  test.setTimeout(120_000)
  const failures = await installPageFailureMonitor(page)
  await startIndependent(page)
  await page.getByLabel('选择数据文件').setInputFiles({ name: 'raw-age.csv', mimeType: 'text/csv', buffer: Buffer.from('age\n20\n25\n30\n35\n40\n') })
  await page.getByRole('button', { name: '导入并创建数据版本' }).click()
  await page.getByRole('tab', { name: '变量视图', exact: true }).click()
  await expect(page.getByRole('heading', { name: '变量类型与识别' })).toBeVisible()
  await page.getByLabel('age的有效类型').selectOption('continuous')
  await page.getByRole('button', { name: '保存变量类型' }).click()
  await expect(page.getByText('已人工确认')).toHaveCount(1)
  await configureMethod(page, '描述统计')
  await expect(page.getByText('原始变量 · 无测量版本')).toBeVisible()
  await expect(page.getByRole('heading', { name: '验证性因子分析（CFA）', exact: true })).toHaveCount(0)
  await page.getByRole('checkbox', { name: 'age', exact: true }).check()
  await configureMethod(page, '描述统计')
  await expect(page.getByRole('checkbox', { name: 'age', exact: true })).toBeChecked()
  await page.reload()
  await configureMethod(page, '描述统计')
  await expect(page.getByRole('checkbox', { name: 'age', exact: true })).toBeChecked()
  let submitted = 0
  let releaseAcceptance: () => void = () => undefined
  let submittedToServer: () => void = () => undefined
  const acceptanceGate = new Promise<void>(resolve => { releaseAcceptance = resolve })
  const serverReceived = new Promise<void>(resolve => { submittedToServer = resolve })
  await page.route('**/empirical-analysis', async route => {
    const response = await route.fetch()
    submittedToServer()
    await acceptanceGate
    await route.fulfill({ response })
  }, { times: 1 })
  page.on('request', request => { if (request.method() === 'POST' && request.url().endsWith('/empirical-analysis')) submitted += 1 })
  const accepted = page.waitForResponse(response => response.request().method() === 'POST' && response.url().endsWith('/empirical-analysis'))
  await page.getByRole('button', { name: '运行描述统计' }).click()
  await serverReceived
  await openAnalysisLibrary(page)
  releaseAcceptance()
  const job = await (await accepted).json() as { id: string; measurementVersion: number | null }
  expect(job.measurementVersion).toBeNull()
  await configureMethod(page, '描述统计')
  await expect(page.getByRole('heading', { name: /描述统计.*本次结果/ })).toBeVisible({ timeout: 60_000 })
  expect(submitted).toBe(1)
  await expectNoHorizontalOverflow(page)
  await expectNoSeriousAccessibilityViolations(page)
  await failures.expectClean()
})

test('@real-r @a11y SEM exposes complete measurement models and preserves edits through undo and reload', async ({ page }) => {
  test.setTimeout(150_000)
  const failures = await installPageFailureMonitor(page, { classifyModelCanvasResizeLoop: true })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await startIndependent(page)
  await page.getByRole('button', { name: '一键导入经典问卷示例项目' }).click()
  await page.getByRole('tab', { name: '量表', exact: true }).click()
  await expect(page.getByText('测量层已完成 · v1')).toBeVisible()
  await openAdvancedSemEditor(page)
  await expect(page.getByText('草稿已保存', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '3 · 估计设置' }).click()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'lavaan (SEM 结构方程)', exact: true }).click()
  const indicators = page.locator('.react-flow__node[data-id^="indicator:"]')
  await expect(indicators).toHaveCount(9)
  await page.getByRole('button', { name: 'lavaan (SEM 结构方程)', exact: true }).click()
  await expect(indicators).toHaveCount(9)
  await page.getByRole('button', { name: '1 · 变量与控制' }).click()
  await page.getByRole('button', { name: '添加高阶潜变量' }).click()
  await expect(page.locator('.react-flow__node[data-id^="higher_factor_"]')).toHaveCount(1)
  await expect(page.locator('.react-flow__edge[data-id^="loading:"]')).toHaveCount(12)
  await page.getByRole('button', { name: '折叠全部指标' }).click()
  await expect(indicators).toHaveCount(0)
  await page.getByRole('button', { name: '展开全部指标' }).click()
  await expect(indicators).toHaveCount(9)
  await page.getByRole('button', { name: '结构图', exact: true }).click()
  await expect(indicators).toHaveCount(0)
  await page.getByRole('button', { name: '完整模型', exact: true }).click()
  await expect(indicators).toHaveCount(9)
  await page.getByLabel('定位并编辑测量因子').selectOption({ label: '总体构念' })
  await expect(page.locator('summary[id^="sem-measurement-higher_factor_"]')).toBeFocused()
  await page.getByRole('button', { name: '删除该高阶潜变量' }).click()
  await expect(page.locator('.react-flow__node[data-id^="higher_factor_"]')).toHaveCount(0)
  await page.getByRole('button', { name: '↩ 撤销', exact: true }).click()
  await expect(page.locator('.react-flow__node[data-id^="higher_factor_"]')).toHaveCount(1)
  await expect(page.getByText('草稿已保存', { exact: true })).toBeVisible()
  await page.reload()
  await openAdvancedSemEditor(page)
  await expect(page.locator('.react-flow__node[data-id^="higher_factor_"]')).toHaveCount(1)
  await expect(indicators).toHaveCount(9)
  await page.getByRole('button', { name: '3 · 估计设置' }).click()
  await page.getByLabel('多组分组变量').selectOption({ label: 'group (group)' })
  await page.getByRole('combobox', { name: '估计器', exact: true }).selectOption('WLSMV')
  await page.getByRole('button', { name: 'lavaan (SEM 结构方程)', exact: true }).click()
  await expect(page.getByRole('combobox', { name: '估计器', exact: true })).toHaveValue('WLSMV')
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'PROCESS (OLS 回归)', exact: true }).click()
  await page.getByRole('button', { name: 'PROCESS (OLS 回归)', exact: true }).click()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'lavaan (SEM 结构方程)', exact: true }).click()
  await expect(page.locator('.react-flow__node[data-id^="higher_factor_"]')).toHaveCount(0)
  await page.getByRole('button', { name: '↩ 撤销', exact: true }).click()
  await page.getByRole('button', { name: '↩ 撤销', exact: true }).click()
  await expect(page.locator('.react-flow__node[data-id^="higher_factor_"]')).toHaveCount(1)
  await expect(page.getByRole('combobox', { name: '估计器', exact: true })).toHaveValue('WLSMV')
  await expect(page.getByLabel('多组分组变量').locator('option:checked')).toContainText('group')
  await expectNoSeriousAccessibilityViolations(page)
  await page.getByRole('button', { name: '专注模式', exact: true }).click()
  await page.locator('.canvas').scrollIntoViewIfNeeded()
  await page.screenshot({ path: 'output/playwright/sem-complete-desktop.png' })
  await page.setViewportSize({ width: 390, height: 844 })
  await expectNoHorizontalOverflow(page)
  await expectNoSeriousAccessibilityViolations(page)
  await page.locator('.canvas').scrollIntoViewIfNeeded()
  await page.screenshot({ path: 'output/playwright/sem-complete-mobile.png' })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole('button', { name: '退出专注模式', exact: true }).click()
  await page.getByLabel('多组分组变量').selectOption('')
  await page.getByRole('combobox', { name: '估计器', exact: true }).selectOption('ML')
  await page.getByRole('button', { name: '1 · 变量与控制' }).click()
  await page.getByLabel('定位并编辑测量因子').selectOption({ label: '总体构念' })
  await page.getByRole('button', { name: '删除该高阶潜变量' }).click()
  await expect(page.getByRole('button', { name: '冻结并确定模型版本' })).toBeEnabled()
  await page.getByRole('button', { name: '冻结并确定模型版本' }).click()
  await expect(page.getByText(/已冻结 Version/)).toBeVisible()
  await page.getByRole('button', { name: '运行模型分析与估计' }).click()
  await expect(page.getByRole('button', { name: '下载结果与复现包' })).toBeVisible({ timeout: 90_000 })
  const loadingDetails = page.getByRole('region', { name: '路径载荷统计详情', exact: true })
  await expect(loadingDetails).toHaveCount(9)
  for (const loading of await loadingDetails.all()) await expect(loading).toContainText('B=')
  await expectNoSeriousAccessibilityViolations(page)
  await failures.expectClean()
})
