import { execFileSync } from 'node:child_process'
import { resolve } from 'node:path'
import { expect, test, type Page } from '@playwright/test'
import { configureMethod, openAdvancedProcessEditor, openDataWorkspace } from './session'
import { expectNoHorizontalOverflow, expectNoSeriousAccessibilityViolations, installPageFailureMonitor } from './quality'

async function openDemo(page: Page) {
  await openDataWorkspace(page)
  await page.getByRole('button', { name: '一键导入经典问卷示例项目' }).click()
  await page.getByRole('tab', { name: '量表', exact: true }).click()
  await expect(page.getByText('测量层已完成 · v1')).toBeVisible()
}

test('@a11y EFA headers and workbook import remain legible, and clearing unloads without deletion', async ({ page }) => {
  test.setTimeout(150_000)
  const failures = await installPageFailureMonitor(page)
  await page.setViewportSize({ width: 1440, height: 1000 })
  await openDemo(page)
  await configureMethod(page, '探索性因子分析（EFA）')
  await expect(page.locator('.analysis-shell-header h1')).toHaveText('探索性因子分析（EFA）')
  for (const [width, theme] of [[1440, '明亮模式'], [390, '暗色模式']] as const) {
    await page.setViewportSize({ width, height: 1000 })
    const summaries = page.locator('.analysis-config-section > summary')
    await expect(summaries).toHaveCount(2)
    const rectangles = await summaries.evaluateAll(elements => elements.map(element => ({ height: element.getBoundingClientRect().height, titleWidth: element.querySelector('strong')?.getBoundingClientRect().width ?? 0 })))
    expect(rectangles.length).toBeGreaterThanOrEqual(2)
    expect(rectangles.every(rect => rect.height < 100 && rect.titleWidth > 110)).toBe(true)
    await expectNoHorizontalOverflow(page)
    await expectNoSeriousAccessibilityViolations(page)
    await summaries.first().scrollIntoViewIfNeeded()
    await page.screenshot({ path: `output/playwright/efa-headers-${width}.png` })
    await page.getByRole('button', { name: theme, exact: true }).click()
  }
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole('tab', { name: '数据', exact: true }).click()
  await page.getByRole('button', { name: '导入 / 替换', exact: true }).click()
  const file = resolve('output/ui-process-rework/two-sheets.xlsx')
  const python = resolve(process.platform === 'win32' ? '.venv/Scripts/python.exe' : '.venv/bin/python')
  execFileSync(python, ['-c', "from openpyxl import Workbook; from pathlib import Path; import sys; p=Path(sys.argv[1]); p.parent.mkdir(parents=True, exist_ok=True); w=Workbook(); w.active.title='sheet1'; w.active.append(['score','age']); [w.active.append([i+1,20+i]) for i in range(30)]; s=w.create_sheet('sheet2'); s.append(['score','age']); [s.append([i+2,21+i]) for i in range(30)]; w.save(p)", file])
  await page.locator('input[type=file]').first().setInputFiles(file)
  const imported = page.waitForResponse(r => r.request().method() === 'POST' && r.url().includes('/datasets/import') && r.ok())
  await page.getByRole('button', { name: '导入并创建数据版本' }).click()
  let dataset = await (await imported).json() as { id: string }
  const sheet = page.getByRole('combobox', { name: /检测到当前工作簿/ })
  await expect(sheet).toBeVisible()
  await expect(page.locator('.dropzone-text')).toContainText('two-sheets.xlsx')
  await sheet.selectOption('sheet2')
  const switched = page.waitForResponse(r => r.request().method() === 'POST' && r.url().includes('/datasets/import') && r.ok())
  await page.getByRole('button', { name: '切换并重新导入', exact: true }).click()
  dataset = await (await switched).json() as { id: string }
  await expect(sheet).toHaveValue('sheet2')
  for (const width of [1440, 390]) {
    await page.setViewportSize({ width, height: 1000 })
    await sheet.scrollIntoViewIfNeeded()
    await expectNoHorizontalOverflow(page)
    await expectNoSeriousAccessibilityViolations(page)
    await page.screenshot({ path: `output/playwright/workbook-import-${width}.png` })
    await page.getByRole('button', { name: width === 1440 ? '明亮模式' : '暗色模式', exact: true }).click()
  }
  page.once('dialog', dialog => dialog.dismiss())
  await page.getByRole('button', { name: '关闭当前数据', exact: true }).click()
  await expect(sheet).toBeVisible()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '关闭当前数据', exact: true }).click()
  await expect(sheet).toHaveCount(0)
  await expect(page.getByRole('button', { name: '关闭当前数据', exact: true })).toHaveCount(0)
  await expect(page.locator('input[type=file]').first()).toHaveValue('')
  await page.reload()
  await expect(page.getByRole('button', { name: '关闭当前数据', exact: true })).toHaveCount(0)
  const retained = await page.request.get(`/api/v1/datasets/${dataset.id}`, { headers: { 'x-researchpath-token': process.env.RESEARCHPATH_E2E_SESSION_TOKEN ?? '' } })
  expect(retained.status()).toBe(200)
  await failures.expectClean()
})

test('@a11y all presets are selectable and custom nodes and arrows support visible reversible edits', async ({ page }) => {
  test.setTimeout(180_000)
  const failures = await installPageFailureMonitor(page, { classifyModelCanvasResizeLoop: true })
  await page.setViewportSize({ width: 1600, height: 1100 })
  await openDemo(page)
  await openAdvancedProcessEditor(page)
  await expect(page.getByText('草稿已保存', { exact: true })).toBeVisible()
  await page.getByText('更换模型 · Model 4 · 单一中介', { exact: true }).click()
  await expect(page.getByRole('group', { name: '官方预设编号', exact: true }).getByRole('button')).toHaveCount(55)
  await page.getByRole('searchbox', { name: '查找官方预设', exact: true }).fill('91')
  await page.getByRole('button', { name: 'Model 91', exact: true }).click()
  await page.getByRole('combobox', { name: '中介数量', exact: true }).selectOption('3')
  const presetSaved = page.waitForResponse(r => r.request().method() === 'PUT' && r.url().endsWith('/draft') && r.request().postDataJSON().model_spec.name.startsWith('Model 91'))
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '应用 Model 91 到画布', exact: true }).click()
  const preset = await (await presetSaved).json()
  expect(preset.modelSpec.moderations).toHaveLength(3)
  expect(preset.modelSpec.nodes.filter((n: { role: string }) => n.role === 'm')).toHaveLength(3)
  await expectNoSeriousAccessibilityViolations(page)
  await page.getByRole('region', { name: '全部官方 PROCESS 预设' }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: 'output/playwright/process-all-presets.png' })
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '自定义构建', exact: true }).click()
  await expect(page.getByText('草稿已保存', { exact: true })).toBeVisible()
  await expect(page.locator('.react-flow__edge')).toHaveCount(0)
  await page.locator('.template-explorer > summary').click()
  // Real HTML drag-and-drop from the variable library into an unoccupied canvas area.
  const canvas = page.getByRole('region', { name: '回归路径模型', exact: true })
  await page.getByRole('button', { name: '选择变量 age', exact: true }).dragTo(canvas, { targetPosition: { x: 60, y: 50 } })
  await expect(page.getByRole('combobox', { name: '新变量角色', exact: true })).toHaveValue('')
  await page.getByRole('combobox', { name: '新变量角色', exact: true }).selectOption('w')
  await page.getByRole('button', { name: '确认放置变量', exact: true }).click()
  await expect(page.getByRole('region', { name: '模型节点 W', exact: true })).toContainText('age')
  await expect(page.locator('.react-flow__edge')).toHaveCount(0)
  await page.getByRole('button', { name: '编辑节点 age', exact: true }).click()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('combobox', { name: '节点角色 age', exact: true }).selectOption('m')
  await expect(page.getByRole('region', { name: '模型节点 M', exact: true })).toContainText('age')
  await page.getByRole('button', { name: '2 · 路径与调节', exact: true }).click()
  await page.getByRole('combobox', { name: '新增路径起点' }).selectOption('node_x')
  await page.getByRole('combobox', { name: '新增路径终点' }).selectOption('node_y')
  await page.getByRole('button', { name: '添加路径', exact: true }).click()
  await page.locator('.react-flow__edge').first().click()
  await page.getByRole('button', { name: '反转箭头', exact: true }).click()
  await expect(page.getByRole('combobox', { name: '连线起点', exact: true })).toHaveValue('node_y')
  await page.getByRole('button', { name: '↩ 撤销', exact: true }).click()
  await expect(page.getByRole('combobox', { name: '连线起点', exact: true })).toHaveValue('node_x')
  await page.getByRole('button', { name: '删除连线', exact: true }).click()
  await expect(page.locator('.react-flow__edge')).toHaveCount(0)
  await expect(page.getByText('草稿已保存', { exact: true })).toBeVisible()
  await page.reload()
  await openAdvancedProcessEditor(page)
  await expect(page.getByText('草稿已保存', { exact: true })).toBeVisible()
  await expect(page.locator('.react-flow__edge')).toHaveCount(0)
  await expect(page.getByRole('region', { name: '模型节点 M', exact: true })).toContainText('age')
  await expect(page.getByRole('button', { name: '冻结并确定模型版本', exact: true })).toBeDisabled()
  await expectNoHorizontalOverflow(page)
  await expectNoSeriousAccessibilityViolations(page)
  await page.screenshot({ path: 'output/playwright/process-custom-editing.png' })
  await failures.expectClean()
})
