import type { EmpiricalAggregationDiagnostic } from './empirical-aggregation'
import type { DiaryMultilevelResult } from './diary-types'
import type { EfaResult } from './efa'
import type { EmpiricalAnalysisOptions, StatisticalMethodExecution } from './empirical-types'
import type { LongitudinalPanelResult } from './longitudinal-types'
import type { StudyPlanEvidenceGraph, StudyPlanResultBinding } from './workflows'
import type { PublicationGate, ReplayDescriptor, ReportFact, ReportingProfileAssessment } from './result-bundle-types'

export interface EmpiricalAnalysisReport {
  reliability?: { method: string; constructs: Array<{ constructId: string; label: string; n: number; itemCount: number; statistics: { alpha: number | null; omega: number | null; ordinalAlpha?: number | null; ordinalOmega?: number | null; reliabilityWarning?: string | null; ordinalReliabilityReason?: string | null }; items: Array<{ itemId: string; correctedItemTotalCorrelation: number | null; alphaIfDeleted: number | null; omegaIfDeleted: number | null }> }> } | null
  schemaVersion: string
  studyPlanBinding?: StudyPlanResultBinding
  evidenceGraph?: StudyPlanEvidenceGraph
  reportId: string
  datasetId: string
  measurementVersionId: string | null
  createdAt: string
  jobStatus: 'queued' | 'running' | 'completed' | 'failed' | 'cancelled'; estimationStatus: 'not_run' | 'succeeded' | 'failed' | 'non_converged' | 'boundary_solution'; inferenceStatus: 'not_available' | 'reliable' | 'needs_review' | 'not_reliable'; publicationEligibility: 'ineligible' | 'conditional' | 'eligible'
  sample: { rowCount: number; itemCompleteCases: number; constructCount: number; measurementAdequacy?: { status: 'adequate' | 'caution'; completeCases: number; itemCount: number; estimatedParameterCount: number; casesPerParameter: number | null; minimumCompleteCasesGuardrail: number; minimumCasesPerParameterGuardrail: number; parameterCountSource: string; interpretation: string; ruleNature: string } }
  missingDataReport?: { rowCount: number; variableCount: number; completeCaseCount: number; incompleteCaseCount: number; anyMissingCellCount: number; patternCount: number; patternsTruncated: boolean; guidance: string; variables: Array<{ id: string; label: string; validCount: number; missingCount: number; missingRate: number | null }>; patterns: Array<{ missingIds: string[]; missingLabels: Record<string, string> | string[]; count: number; proportion: number | null }>; littleMcar: { available: boolean; reason?: string; statistic?: number | null; degreesOfFreedom?: number; pValue?: number | null; variableIds?: string[]; variableLabels?: string[]; n?: number; patternCount?: number; emConverged?: boolean; emIterations?: number; method?: string } } | null
  sampleVersion?: { sampleVersionId: string; sampleHash: string; qualityRunId: string; includedCount: number; excludedCount: number }
  options: EmpiricalAnalysisOptions
  publicationEligible?: boolean; requiresManualReview?: boolean; publicationEligibilityReasons?: string[]
  sampleFlow?: { original: number; selected?: number; included: number; excluded: number; missingRows?: number; finalN?: number; missingMethod: string; variableMissingCounts?: Record<string, number>; missingPatterns?: Array<{ pattern: string; count: number }> }
  academicInterpretation?: string
  apaTables?: string
  reportFacts?: ReportFact[]
  reportingProfileAssessments?: ReportingProfileAssessment[]
  replay?: ReplayDescriptor
  publicationGate?: PublicationGate
  descriptives: Array<{ id: string; label: string; n: number; missing: number; mean: number | null; sd: number | null; minimum: number | null; maximum: number | null; skewness: number | null; kurtosis: number | null; outlierCount: number }>
  frequencies: Array<{ id: string; label: string; validCount: number; levels: Array<{ level: string; count: number; proportion: number }> }>
  correlations: { variables: Array<{ id: string; label: string }>; coefficients: Array<Array<number | null>>; pValues: Array<Array<number | null>>; pValuesRaw?: Array<Array<number | null>>; pValuesAdjusted?: Array<Array<number | null>>; pValueDisplay?: 'adjusted' | 'raw'; multiplicity?: { familyId: string; familySize: number; adjustment: 'none' | 'holm' | 'BH'; scope: string; confidenceIntervalsAdjusted: boolean }; counts: number[][]; ciLower?: Array<Array<number | null>>; ciUpper?: Array<Array<number | null>>; confidenceLevel?: number; confidenceIntervalMethod?: string; method: string; inferenceAvailable?: boolean; inferenceReason?: string | null; dependenceStructure?: 'independent' | 'nested' }
  multiplicity?: { familyId: string; scope: string[]; adjustment: 'none' | 'holm' | 'BH'; globalAdjustmentApplied: boolean; components: string[] }
  paperSummaryTable?: { title: string; variables: Array<{ id: string; label: string }>; rows: Array<{ id: string; label: string; n: number; mean: number | null; sd: number | null; alpha: number | null; omega: number | null; correlations: Array<number | null>; pValues: Array<number | null>; counts: number[]; pValuesRaw?: Array<number | null>; pValuesAdjusted?: Array<number | null>; ciLower: Array<number | null>; ciUpper: Array<number | null> }>; correlationMethod: string; confidenceLevel: number; pValueDisplay?: 'adjusted' | 'raw'; multiplicity?: EmpiricalAnalysisReport['correlations']['multiplicity'] } | null
  commonMethodBias: { ulmc?: Record<string, unknown>; available: boolean; completeCases: number; itemCount: number; firstFactorVariancePercent: number | null; eigenvaluesAboveOne: number; method: string }
  factorability: { kmo: number | null; bartlett: { statistic: number | null; degreesOfFreedom: number; pValue: number | null }; completeCases: number }
  efa: EfaResult
  cfa: { available: boolean; converged?: boolean; completeCases?: number; publicationEligible?: boolean; requiresManualReview?: boolean; publicationEligibilityReasons?: string[]; methodExecution?: StatisticalMethodExecution; estimatedParameterCount?: number; casesPerParameter?: number | null; validForConfirmatoryInterpretation?: boolean; sampleAdequacy?: EmpiricalAnalysisReport['sample']['measurementAdequacy']; chiSquare?: number | null; degreesOfFreedom?: number; pValue?: number | null; cfi?: number | null; tli?: number | null; rmsea?: number | null; srmr?: number | null; rmseaCiLower?: number | null; rmseaCiUpper?: number | null; estimator?: string; reason?: string; itemIds?: string[]; standardizedLoadings?: number[]; factorCorrelations?: number[][]; constructIds?: string[] }
  validity: { methodExecution?: StatisticalMethodExecution; constructs: Array<{ constructId: string; label: string; scoreId: string; alpha: number | null; omega: number | null; compositeReliability: number | null; averageVarianceExtracted: number | null; sqrtAve: number | null; discriminantValidityPass: boolean | null; discriminantValidityStatus?: 'pass' | 'fail' | 'not_evaluable'; loadingSource: string; fallbackApplied?: boolean }>; constructLabels: string[]; fornellCorrelationSource?: string; htmtAvailable?: boolean; htmtReason?: string | null; htmtCorrelationSource?: 'pearson' | 'polychoric' | 'unavailable_mixed_item_scales'; htmtMethodExecution?: StatisticalMethodExecution; htmtInferenceAvailable?: boolean; htmtInferenceReason?: string | null; htmtConfidenceLevel?: number; htmtConfidenceIntervalMethod?: string; fornellLarcker: Array<Array<number | null>>; htmt: Array<Array<number | null>>; htmtCiLower?: Array<Array<number | null>> | null; htmtCiUpper?: Array<Array<number | null>> | null }
  measurementInvariance?: null | { available: boolean; reason?: string; sampleSize?: number; missingMethod?: string; groupVariable?: string; groupLevels?: string[]; groupSizes?: number[]; models?: Record<string, null | { chiSquare: number | null; chiSquareScaled: number | null; df: number | null; pValue: number | null; cfi: number | null; cfiRobust: number | null; tli: number | null; tliRobust: number | null; rmsea: number | null; rmseaRobust: number | null; srmr: number | null }>; comparisons?: Record<string, { deltaChiSquare: number | null; deltaDf: number | null; pValue: number | null; deltaCfi: number | null; deltaRmsea: number | null; fitIndexBasis: string }> }
  advancedMeasurementBoundary?: { executedInBaseReport: false; availableThrough: 'advanced_workbench'; sliceId: 'questionnaire_measurement.esem_bifactor_irt'; methods: Array<'ESEM' | 'Bifactor' | 'IRT' | 'DIF'>; requirement: string }
  groupComparison: null | { groupVariableId: string; groupLabel: string; levels: string[]; analysisPolicy?: { primaryModel: string; sensitivityModel: string; selectionRule: string; brownForsytheRole: string }; multiplicity?: { adjustment: 'none' | 'holm' | 'BH'; primaryFamilyId: string; primaryFamilySize: number; robustFamilyId: string; robustFamilySize: number; assumptionFamilyId: string; assumptionFamilySize: number; pairwiseScope: string; confidenceIntervalsAdjustedAcrossConstructs: boolean; globalFamilyId?: string; globalScope?: string; globalAdjustment?: 'none' | 'holm' | 'BH'; globalAdjustmentApplied?: boolean }; results: Array<{ id: string; label: string; test: string; statistic: number | null; df1: number | null; df2: number | null; pValue: number | null; pValueRaw?: number | null; pValueAdjusted?: number | null; multiplicityFamilyId?: string; multiplicityFamilySize?: number; pAdjustMethod?: 'none' | 'holm' | 'BH'; effectSize: number | null; effectSizeType: string; confidenceLevel?: number; unavailable?: boolean; reason?: string; effectSizeCiLower?: number | null; effectSizeCiUpper?: number | null; effectSizeConfidenceLevel?: number; effectSizeCiMethod?: string; omegaSquared?: number | null; groups: Array<{ level: string; n: number; mean: number | null; sd: number | null }>; pairwiseTukey?: Array<{ comparison: string; difference: number; lower: number; upper: number; pValue: number; confidenceLevel?: number }>; pairwiseBonferroni?: Array<{ comparison: string; pValue: number }>; assumptionTests?: { brownForsythe: { statistic: number | null; df1: number | null; df2: number | null; pValue: number | null } }; robustTest?: { method: string; statistic: number | null; df1: number | null; df2: number | null; pValue: number | null; role?: 'sensitivity' }; pairwiseGamesHowell?: Array<{ comparison: string; difference: number | null; standardError: number | null; degreesOfFreedom: number | null; lower: number | null; upper: number | null; pValue: number | null; confidenceLevel?: number }> }> }
  aggregationDiagnostics: null | { groupVariableId: string; groupLabel: string; method: string; guidance: string; constructs: EmpiricalAggregationDiagnostic[] }
  hierarchicalRegression: null | { outcomeVariableId: string; outcomeLabel: string; n: number; estimand?: string; primaryAnalysis?: { method: string; role: 'primary'; confidenceLevel: number; selectionRule: string }; publicationEligible?: boolean; requiresManualReview?: boolean; publicationEligibilityReasons?: string[]; sampleFlow?: EmpiricalAnalysisReport['sampleFlow']; underdetermined?: boolean; blocks: Array<{ block: number; formula: string; rSquared: number | null; adjustedRSquared: number | null; coefficients: Array<{ term: string; label: string; estimate: number | null; standardError: number | null; statistic: number | null; pValue: number | null; lower: number | null; upper: number | null; vif: number | null; standardizedEstimate?: number | null; cohenF2?: number | null; pValueRaw?: number | null; pValueAdjusted?: number | null; globalPValue?: number | null; estimandId?: string; analysisRole?: string; declarationStatus?: string; multiplicityFamilyId?: string; multiplicityFamilySize?: number; multiplicityAdjustmentN?: number; pAdjustMethod?: 'none' | 'holm' | 'BH' }> }>; change: { deltaRSquared: number | null; statistic: number | null; df1: number | null; df2: number | null; pValue: number | null }; robustness?: { hc3Execution?: { available?: boolean; requestedMethod?: string; executedMethod?: string; requested: string; executed: string; fallbackApplied: boolean; fallbackReason?: string; maximumLeverage?: number | null; rank?: number | null; parameterCount?: number | null; confidenceLevel?: number }; standardErrorComparison: Array<{ term: string; label: string; estimate: number | null; classicStandardError: number | null; classicPValue: number | null; classicLower: number | null; classicUpper: number | null; hc3StandardError: number | null; hc3PValue: number | null; hc3Lower: number | null; hc3Upper: number | null }>; influence: { cookDistanceCutoff: number | null; leverageCutoff: number | null; influentialCount: number; retainedCount: number; maximumCookDistance: number | null; maximumLeverage: number | null; rule: string }; coefficientStability: Array<{ term: string; label: string; unadjustedEstimate: number | null; adjustedEstimate: number | null; withoutInfluentialEstimate: number | null; signChangedAfterControls: boolean | null; signChangedWithoutInfluential: boolean | null }> }; relativeImportance?: { available: boolean; reason?: string; n?: number; outcomeId?: string; outcomeLabel?: string; predictorCount?: number; controlIds?: string[]; baseRSquared?: number | null; fullRSquared?: number | null; incrementalRSquared?: number | null; contributionSum?: number | null; subsetModelCount?: number; method?: string; rows?: Array<{ id: string; label: string; contribution: number | null; percentIncrementalRSquared: number | null; rank: number }> } }
  responseSurface?: null | { available: boolean; confidenceLevel?: number; reason?: string; outcomeId?: string; outcomeLabel?: string; xId?: string; xLabel?: string; zId?: string; zLabel?: string; n?: number; formula?: string; rSquared?: number | null; adjustedRSquared?: number | null; centering?: { xMean: number | null; zMean: number | null }; coefficients?: Array<{ term: string; label: string; estimate: number | null; standardError: number | null; statistic: number | null; pValue: number | null; lower: number | null; upper: number | null }>; surfaceTests?: Array<{ id: string; label: string; estimate: number | null; standardError: number | null; statistic: number | null; pValue: number | null; lower: number | null; upper: number | null }>; stationaryPoint?: { xCentered: number | null; zCentered: number | null; xRaw: number | null; zRaw: number | null; hessianEigenvalues: Array<number | null> }; grid?: Array<{ x: number; z: number; predicted: number }>; method?: string }
  longitudinalPanel?: LongitudinalPanelResult | null
  diaryMultilevel?: DiaryMultilevelResult | null
  warnings: Array<{ code: string; severity: 'warning'; message: string }>
  provenance: Record<string, unknown>
}
