"""Generate the browser preset manifest from the authoritative execution catalog."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "apps/api"))

from app.process_catalog import (  # noqa: E402
    EXECUTABLE_PROCESS_MODELS,
    PROCESS_MODEL_BITS,
    PROCESS_SPECIAL_RULES,
    _mediator_limits,
)

TARGET = ROOT / "apps/web/src/components/model-builder/processPresets.generated.ts"


def render() -> str:
    lines = ["// Generated by scripts/generate-process-templates.py; do not edit.",
             "// Source: app.process_catalog; verified against a user-provided official PROCESS for R 5.0 copy.",
             "export const processPresets = ["]
    for number, bits in PROCESS_MODEL_BITS.items():
        if number not in EXECUTABLE_PROCESS_MODELS:
            continue
        minimum, maximum = _mediator_limits(number)
        item = {"number": number, "bits": bits, "minM": minimum, "maxM": maximum,
                "firstOnly": number in PROCESS_SPECIAL_RULES["firstMediatorOnlyForW"],
                "lastOnly": number in PROCESS_SPECIAL_RULES["lastMediatorOnlyForW"],
                "serialModeration": number in PROCESS_SPECIAL_RULES["serialEdgesModeratedByW"]}
        lines.append("  " + json.dumps(item, separators=(",", ":")) + ",")
    return "\n".join([*lines, "] as const", ""])


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != content:
            raise SystemExit("PROCESS presets are stale; run scripts/generate-process-templates.py")
        print("PROCESS browser presets match the executable catalog (55 active models).")
    else:
        TARGET.write_text(content, encoding="utf-8", newline="\n")
