"""Execute case-local SUT adapters and attest their outputs.

A SUT adapter lives at ``sut/run.py`` inside a golden case. It must call the
production implementation and write ``sut/normalized-output.json``. Reference
or expected outputs are deliberately never used as a fallback: copying either
would turn an end-to-end check into a circular self-comparison.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Tuple

import yaml

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
GOLDENS_DIR = PROJECT_ROOT / "tests" / "goldens"


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def run_sut_for_case(case_dir: Path) -> Tuple[bool, str]:
    """Run a production SUT adapter in isolation and publish its attested output."""
    manifest_path = case_dir / "manifest.yaml"
    if not manifest_path.is_file():
        return False, "manifest.yaml missing"

    # Parse early so malformed manifests fail before any output is touched.
    with manifest_path.open("r", encoding="utf-8") as stream:
        yaml.safe_load(stream)

    runner = case_dir / "sut" / "run.py"
    if not runner.is_file():
        return False, "production SUT adapter sut/run.py is missing"

    with tempfile.TemporaryDirectory(prefix="researchpath-sut-") as temporary:
        isolated_case = Path(temporary) / "case"
        shutil.copytree(case_dir, isolated_case)
        isolated_output = isolated_case / "sut" / "normalized-output.json"
        isolated_provenance = isolated_case / "sut" / "provenance.json"
        isolated_output.unlink(missing_ok=True)
        isolated_provenance.unlink(missing_ok=True)

        environment = os.environ.copy()
        environment["RESEARCHPATH_PROJECT_ROOT"] = str(PROJECT_ROOT)
        completed = subprocess.run(
            [sys.executable, str(isolated_case / "sut" / "run.py")],
            cwd=str(isolated_case),
            env=environment,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=120,
        )
        if completed.returncode != 0:
            detail = (completed.stderr or completed.stdout).strip()
            return False, f"SUT adapter failed with exit code {completed.returncode}: {detail}"
        if not isolated_output.is_file():
            return False, "SUT adapter did not create sut/normalized-output.json"

        try:
            json.loads(isolated_output.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            return False, f"SUT adapter produced invalid JSON: {exc}"

        sut_dir = case_dir / "sut"
        sut_dir.mkdir(parents=True, exist_ok=True)
        output = sut_dir / "normalized-output.json"
        shutil.copy2(isolated_output, output)
        provenance = {
            "schemaVersion": 1,
            "generatedAt": datetime.now(timezone.utc).isoformat(),
            "runnerPath": "sut/run.py",
            "runnerSha256": _sha256(runner),
            "manifestSha256": _sha256(manifest_path),
            "outputSha256": _sha256(output),
        }
        (sut_dir / "provenance.json").write_text(
            json.dumps(provenance, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
    return True, "SUT output generated by production adapter and attested"


def main() -> int:
    parser = argparse.ArgumentParser(description="Run production SUT adapters for Golden Cases")
    parser.add_argument("--capability", type=str, help="Capability ID to run")
    parser.add_argument("--case", type=str, help="Specific Case ID to run")
    parser.add_argument("--all", action="store_true", help="Run all golden cases")
    args = parser.parse_args()

    cases: List[Path] = []
    if args.capability:
        cap_dir = GOLDENS_DIR / args.capability
        if cap_dir.exists():
            cases.extend(d for d in (cap_dir / "cases").iterdir() if d.is_dir())
    elif args.case:
        cases.extend(p for p in GOLDENS_DIR.glob(f"**/cases/{args.case}") if p.is_dir())
    elif args.all:
        cases.extend(
            p
            for p in GOLDENS_DIR.glob("**/cases/*")
            if p.is_dir() and (p / "manifest.yaml").is_file()
        )

    if not cases:
        print("No cases targeted for SUT execution.")
        return 1

    print(f"Running SUT adapters for {len(cases)} case(s)...")
    success_count = 0
    for case_dir in cases:
        ok, message = run_sut_for_case(case_dir)
        print(f" {'[PASS]' if ok else '[FAIL]'} {case_dir.name}: {message}")
        success_count += int(ok)

    print(f"\nSUT execution summary: {success_count}/{len(cases)} cases generated.")
    return 0 if success_count == len(cases) else 1


if __name__ == "__main__":
    sys.exit(main())
